"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, Eye, LoaderCircle, Sparkles } from "lucide-react";
import { api, AICandidateContext, AICopilotStatus, AIEvidenceCandidate, AIEvidenceRun, AISourceDocument, Evidence, Project } from "@/lib/real-api";

type Props={project:Project;evidence:Evidence[];onChanged:()=>Promise<void>};
type EditDraft={claim:string;verbatim_quote:string;scope:string;limitations:string;reviewer_note:string;manual_source_verified:boolean};

const runLabels:Record<AIEvidenceRun["status"],string>={PENDING:"等待分析",RUNNING:"分析中",SUCCEEDED:"已生成候选",PARTIAL:"部分成功",ABSTAINED:"材料不足",FAILED:"调用失败",TIMED_OUT:"调用超时",INTERRUPTED:"运行已中断"};
const citationLabels:Record<AIEvidenceCandidate["citation_verification_status"],string>={VERIFIED:"原文引用已定位",NEEDS_MANUAL_VERIFICATION:"需要人工核验来源",INVALID:"引用无效"};
const reviewLabels:Record<AIEvidenceCandidate["review_status"],string>={PENDING_REVIEW:"待人工复核",ACCEPTED:"已接受",EDITED_AND_ACCEPTED:"编辑后接受",REJECTED:"已拒绝"};

export function EvidenceCopilotPanel({project,evidence,onChanged}:Props){
  const [status,setStatus]=useState<AICopilotStatus|null>(null),[sources,setSources]=useState<AISourceDocument[]>([]),[runs,setRuns]=useState<AIEvidenceRun[]>([]);
  const [sourceId,setSourceId]=useState(""),[sourceName,setSourceName]=useState(""),[sourceText,setSourceText]=useState(""),[sourceUrl,setSourceUrl]=useState(""),[sourceFile,setSourceFile]=useState<File|null>(null),[evidenceId,setEvidenceId]=useState("");
  const [busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[context,setContext]=useState<AICandidateContext|null>(null),[editing,setEditing]=useState<Record<string,EditDraft>>({});
  const draftEvidence=useMemo(()=>evidence.filter(item=>item.status==="draft"),[evidence]);

  const reload=useCallback(async()=>{
    const [nextStatus,nextSources,nextRuns]=await Promise.all([
      api<AICopilotStatus>("/api/v1/ai/evidence-copilot/status"),
      api<AISourceDocument[]>(`/api/v1/projects/${project.id}/ai/sources`),
      api<AIEvidenceRun[]>(`/api/v1/projects/${project.id}/ai/evidence-runs`),
    ]);
    setStatus(nextStatus);setSources(nextSources);setRuns(nextRuns);setSourceId(current=>current||nextSources[0]?.id||"");
  },[project.id]);
  useEffect(()=>{setError("");void reload().catch(reason=>setError(reason instanceof Error?reason.message:"AI助手状态读取失败"))},[reload]);

  const perform=async(name:string,task:()=>Promise<void>,success:string)=>{if(busy)return;setBusy(name);setError("");setMessage("");try{await task();setMessage(success)}catch(reason){setError(reason instanceof Error?reason.message:"操作失败")}finally{setBusy("")}};
  const createText=(event:FormEvent)=>{event.preventDefault();void perform("source-text",async()=>{const created=await api<AISourceDocument>(`/api/v1/projects/${project.id}/ai/sources/text`,{method:"POST",body:JSON.stringify({source_name:sourceName,text:sourceText})});setSourceName("");setSourceText("");await reload();setSourceId(created.id)},"授权文本已建立来源记录；尚未调用AI。")};
  const createUrl=(event:FormEvent)=>{event.preventDefault();void perform("source-url",async()=>{const created=await api<AISourceDocument>(`/api/v1/projects/${project.id}/ai/sources/url`,{method:"POST",body:JSON.stringify({url:sourceUrl})});setSourceUrl("");await reload();setSourceId(created.id)},"公开URL正文已通过现有安全导入建立来源记录；尚未调用AI。")};
  const createFile=(event:FormEvent)=>{event.preventDefault();if(!sourceFile)return;void perform("source-file",async()=>{const body=new FormData();body.append("file",sourceFile);const created=await api<AISourceDocument>(`/api/v1/projects/${project.id}/ai/sources/file`,{method:"POST",body});setSourceFile(null);await reload();setSourceId(created.id)},"授权文件已建立来源记录并计算SHA-256；尚未调用AI。")};
  const createFromEvidence=()=>void perform("source-evidence",async()=>{const created=await api<AISourceDocument>(`/api/v1/projects/${project.id}/ai/sources/from-evidence`,{method:"POST",body:JSON.stringify({evidence_id:evidenceId})});setEvidenceId("");await reload();setSourceId(created.id)},"draft Evidence已复制为独立AI来源；原Evidence未改变。")
  const startRun=()=>void perform("run",async()=>{if(!sourceId)throw new Error("请先选择来源材料");await api<AIEvidenceRun>(`/api/v1/projects/${project.id}/ai/evidence-runs`,{method:"POST",body:JSON.stringify({source_document_id:sourceId})});await reload()},"AI运行已结束；候选内容仍未进入正式Evidence，也未影响Gate。")

  const beginEdit=(candidate:AIEvidenceCandidate)=>setEditing(current=>({...current,[candidate.id]:{claim:candidate.claim,verbatim_quote:candidate.verbatim_quote,scope:candidate.scope,limitations:candidate.limitations,reviewer_note:candidate.reviewer_note,manual_source_verified:candidate.source_manually_verified}}));
  const review=(candidate:AIEvidenceCandidate,action:"ACCEPT"|"EDIT_AND_ACCEPT"|"REJECT")=>{
    const draft=editing[candidate.id]??{claim:candidate.claim,verbatim_quote:candidate.verbatim_quote,scope:candidate.scope,limitations:candidate.limitations,reviewer_note:"",manual_source_verified:false};
    if(action!=="REJECT"&&!window.confirm("接受后将创建正式Evidence、增加项目revision，并使旧Gate与Decision失效。是否继续？"))return;
    void perform(`review-${candidate.id}`,async()=>{
      const payload={action,reviewer_note:draft.reviewer_note,manual_source_verified:draft.manual_source_verified,...(action==="EDIT_AND_ACCEPT"?{claim:draft.claim,verbatim_quote:draft.verbatim_quote,scope:draft.scope,limitations:draft.limitations}:{})};
      await api(`/api/v1/projects/${project.id}/ai/evidence-candidates/${candidate.id}/review`,{method:"POST",headers:{"Idempotency-Key":`review-${crypto.randomUUID()}`,"If-Match":String(project.revision)},body:JSON.stringify(payload)});
      await onChanged();await reload();
    },action==="REJECT"?"候选已拒绝；项目revision与Gate未改变。":"人工复核已创建正式Evidence；请重新检查项目revision和失效结论。")
  };
  const showContext=(candidate:AIEvidenceCandidate)=>void perform(`context-${candidate.id}`,async()=>setContext(await api<AICandidateContext>(`/api/v1/projects/${project.id}/ai/evidence-candidates/${candidate.id}/context`)),"已显示引用上下文；文字存在不代表来源本身正确。")

  return <section className="copilot-panel" aria-labelledby="copilot-title">
    <header><div><p className="section-kicker">Evidence Copilot · candidate only</p><h3 id="copilot-title">AI提取候选证据</h3><p>AI只负责从当前授权材料中提出候选Evidence；每条内容必须核对原文并由负责人确认，才能影响项目。</p></div><span className={`meta-chip ${status?.configured?"":"warning"}`}>{status?.configured?`${status.provider} · ${status.model}`:"未配置AI"}</span></header>
    <div className={`service-status ${status?.configured?"available":"unavailable"}`} role="status">{status?.configured?<CheckCircle2 className="h-5 w-5"/>:<AlertTriangle className="h-5 w-5"/>}<div><strong>{status?.message??"正在读取服务端配置"}</strong><p>模型仅在用户点击后处理当前所选材料；不会访问材料内链接，不会自动确认、关联或改变Gate。</p></div></div>
    {error?<div className="copilot-message error" role="alert">{error}</div>:null}{message?<div className="copilot-message" role="status" aria-live="polite">{message}</div>:null}
    <details className="copilot-source" open={sources.length===0}><summary>1. 建立授权来源</summary><div className="copilot-source-grid">
      <form onSubmit={createText}><strong>粘贴文本</strong><label className="form-field"><span>来源名称</span><input required minLength={2} value={sourceName} onChange={event=>setSourceName(event.target.value)}/></label><label className="form-field"><span>授权材料正文</span><textarea required value={sourceText} onChange={event=>setSourceText(event.target.value)}/></label><button className="secondary-action" disabled={!!busy}>建立文本来源</button></form>
      <form onSubmit={createFile}><strong>文件</strong><p>.txt、.md、.docx、可提取文字的.pdf；最大5MB。</p><input aria-label="AI来源文件" required type="file" accept=".txt,.md,.docx,.pdf" onChange={event=>setSourceFile(event.target.files?.[0]??null)}/><button className="secondary-action" disabled={!!busy||!sourceFile}>建立文件来源</button></form>
      <form onSubmit={createUrl}><strong>单个公开URL</strong><p>只处理用户授权且公开可访问的正文，复用现有SSRF与重定向检查。</p><input required type="url" value={sourceUrl} onChange={event=>setSourceUrl(event.target.value)} placeholder="https://公开页面"/><button className="secondary-action" disabled={!!busy}>建立URL来源</button></form>
      <div><strong>现有draft Evidence</strong><p>不会改写或自动确认原Evidence。</p><select aria-label="选择draft Evidence" value={evidenceId} onChange={event=>setEvidenceId(event.target.value)}><option value="">请选择</option>{draftEvidence.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select><button type="button" className="secondary-action" disabled={!!busy||!evidenceId} onClick={createFromEvidence}>复制为AI来源</button></div>
    </div></details>
    <div className="copilot-run-controls"><label className="form-field"><span>2. 选择本次材料</span><select aria-label="AI来源材料" value={sourceId} onChange={event=>setSourceId(event.target.value)}><option value="">请选择</option>{sources.map(source=><option key={source.id} value={source.id}>{source.source_name} · {source.source_kind} · SHA {source.sha256.slice(0,10)}</option>)}</select></label><button type="button" className="primary-action" disabled={!!busy||!sourceId||!status?.configured} onClick={startRun}>{busy==="run"?<LoaderCircle className="h-4 w-4 animate-spin"/>:<Sparkles className="h-4 w-4"/>}主动开始分析</button></div>
    <p className="copilot-boundary">每次运行有输入、候选数量与超时上限；无无限重试。Structured Output只约束字段，不证明内容真实。</p>
    <div className="copilot-runs">{runs.length===0?<div className="empty-inline">尚无AI运行。手工Evidence导入与确认流程仍可独立使用。</div>:runs.map(run=><article className="copilot-run" key={run.id}><header><div><strong>{runLabels[run.status]}</strong><small>{run.provider} · {run.model} · {run.prompt_version} · {run.output_schema_version}</small></div><span className="meta-chip">{run.candidates.length} 条候选</span></header>{run.abstain_reason?<p className="copilot-abstain">{run.abstain_reason}</p>:null}{run.sanitized_error_message?<p className="copilot-abstain">{run.sanitized_error_message}</p>:null}<div className="copilot-candidates">{run.candidates.map(candidate=>{
        const draft=editing[candidate.id];const pending=candidate.review_status==="PENDING_REVIEW";return <section className="copilot-candidate" key={candidate.id}><div className="copilot-candidate-meta"><span>{citationLabels[candidate.citation_verification_status]}</span><span>{reviewLabels[candidate.review_status]}</span><span>AI建议等级 {candidate.suggested_grade}（非最终评级）</span></div>{draft?<div className="form-grid"><label className="form-field form-field-wide"><span>候选主张</span><textarea value={draft.claim} onChange={event=>setEditing(current=>({...current,[candidate.id]:{...draft,claim:event.target.value}}))}/></label><label className="form-field form-field-wide"><span>原文引用</span><textarea value={draft.verbatim_quote} onChange={event=>setEditing(current=>({...current,[candidate.id]:{...draft,verbatim_quote:event.target.value}}))}/></label><label className="form-field"><span>适用范围</span><textarea value={draft.scope} onChange={event=>setEditing(current=>({...current,[candidate.id]:{...draft,scope:event.target.value}}))}/></label><label className="form-field"><span>限制</span><textarea value={draft.limitations} onChange={event=>setEditing(current=>({...current,[candidate.id]:{...draft,limitations:event.target.value}}))}/></label><label className="form-field form-field-wide"><span>复核说明</span><input value={draft.reviewer_note} onChange={event=>setEditing(current=>({...current,[candidate.id]:{...draft,reviewer_note:event.target.value}}))}/></label>{candidate.citation_verification_status==="NEEDS_MANUAL_VERIFICATION"?<label className="copilot-checkbox"><input type="checkbox" checked={draft.manual_source_verified} onChange={event=>setEditing(current=>({...current,[candidate.id]:{...draft,manual_source_verified:event.target.checked}}))}/><span>我已查看原文件并人工核对该来源引用</span></label>:null}</div>:<><h4>{candidate.claim}</h4><blockquote>{candidate.verbatim_quote}</blockquote><dl><div><dt>来源定位</dt><dd>{candidate.source_locator}</dd></div><div><dt>适用范围</dt><dd>{candidate.scope}</dd></div><div><dt>限制</dt><dd>{candidate.limitations}</dd></div><div><dt>不确定性</dt><dd>{candidate.uncertainty_reasons||"未填写"}</dd></div><div><dt>模型自报提示</dt><dd>{candidate.confidence_indicator}（不是正确概率）</dd></div></dl></>}
        <div className="copilot-actions"><button type="button" className="secondary-action" disabled={!!busy} onClick={()=>showContext(candidate)}><Eye className="h-4 w-4"/>查看上下文</button>{pending&&candidate.citation_verification_status!=="INVALID"?<><button type="button" className="secondary-action" disabled={!!busy||candidate.citation_verification_status==="NEEDS_MANUAL_VERIFICATION"} onClick={()=>review(candidate,"ACCEPT")}>接受</button><button type="button" className="secondary-action" disabled={!!busy} onClick={()=>draft?review(candidate,"EDIT_AND_ACCEPT"):beginEdit(candidate)}>{draft?"确认编辑后接受":"编辑后接受"}</button></>:null}{pending?<button type="button" className="secondary-action" disabled={!!busy} onClick={()=>review(candidate,"REJECT")}>拒绝</button>:null}{candidate.final_evidence_id?<span className="meta-chip">正式Evidence {candidate.final_evidence_id}</span>:null}</div>
      </section>})}</div></article>)}</div>
    {context?<aside className="copilot-context" aria-label="候选引用上下文"><header><strong>引用上下文</strong><button type="button" aria-label="关闭引用上下文" onClick={()=>setContext(null)}>×</button></header><p>{context.warning}</p><pre>{context.context}</pre><small>segment {context.segment_id??"未定位"} · {JSON.stringify(context.locator)}</small></aside>:null}
  </section>
}
