"use client";

import Link from "next/link";
import { ArrowRight, Check, Clock3, Download, ShieldAlert } from "lucide-react";
import { useDecision } from "@/components/decision/decision-provider";
import { DataBoundary, WorkspaceHeading, recommendationLabel } from "@/components/decision/workspace-ui";

export default function DecisionPage(){const {state}=useDecision();const {decision,project}=state;const test=state.tests.find(x=>x.id===decision.testId);const risks=state.assumptions.filter(x=>decision.dangerousAssumptionIds.includes(x.id));return <div className="page-frame"><WorkspaceHeading eyebrow="Pre-investment brief" title="新品投前决策单" description="一页内说明这笔钱该不该花、依据是什么、限制在哪里，以及负责人最终作出了什么决定。" actions={<button className="secondary-action" disabled><Download className="h-4 w-4"/>导出（规划）</button>}/><DataBoundary/><article className="decision-sheet" data-guide="decision"><header><div><span className="simulation-chip">{project.isDemo?"模拟决策单":"真实项目草稿"} · {decision.id}</span><h2>{project.name}</h2><p>{project.stage} · 决策日期 {decision.decidedAt}</p></div><div className={`decision-verdict ${decision.recommendation}`}><span>系统建议</span><strong>{recommendationLabel[decision.recommendation]}</strong><small>置信程度：{decision.confidence==="high"?"较高":decision.confidence==="medium"?"中等":"较低"}</small></div></header><div className="decision-sheet-grid"><section><DecisionField label="下一笔计划投入" value={`${project.nextAction || "待填写"}${project.nextInvestmentAmount===null?"":` · ¥${project.nextInvestmentAmount.toLocaleString("zh-CN")}`}`}/><DecisionField label="判断依据" value={decision.rationale}/><DecisionField label="置信程度限制" value={decision.confidenceLimit} warning/><div className="mt-6"><p className="field-label">当前最危险假设</p><div className="mt-3 space-y-3">{risks.length?risks.map(item=><div key={item.id} className="decision-risk"><ShieldAlert className="h-4 w-4"/><div><strong>{item.statement}</strong><p>{item.errorCost}</p></div></div>):<p className="empty-inline">数据不足，尚未识别关键假设。</p>}</div></div></section><aside><p className="field-label">最低成本下一项验证</p>{test?<div className="next-test-card"><span>{test.id}</span><h3>{test.primaryVariable}</h3><p>{test.hypothesis}</p><div><strong>¥{test.budget.toLocaleString("zh-CN")}</strong><small>{test.duration} · {test.sample}</small></div></div>:<p className="empty-inline">尚无可执行实验建议。</p>}<p className="field-label mt-6">追溯信息</p><div className="trace-list"><p><span>证据ID</span><strong>{decision.evidenceIds.join("、")||"无"}</strong></p><p><span>规则版本</span><strong>{decision.ruleVersion}</strong></p><p><span>模型版本</span><strong>{decision.modelVersion}</strong></p><p><span>负责人</span><strong>{decision.owner}</strong></p></div></aside></div><footer><div><Clock3 className="h-4 w-4"/><span>人工决定：{decision.humanDecision==="pending"?"待负责人确认":recommendationLabel[decision.humanDecision]}</span></div><p>AI建议不自动改变预算、订单或审批状态。</p></footer></article><div className="mt-6 flex justify-end"><Link href="/results" className="primary-action">回填真实结果<ArrowRight className="h-4 w-4"/></Link></div></div>}
function DecisionField({label,value,warning=false}:{label:string;value:string;warning?:boolean}){return <div className={`decision-field ${warning?"warning":""}`}>{warning?<ShieldAlert className="h-4 w-4"/>:<Check className="h-4 w-4"/>}<div><span>{label}</span><p>{value}</p></div></div>}
