"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { AlertTriangle, ArrowRight, Ban, CheckCircle2, ExternalLink, Filter, GitBranch, Grid2X2, ListFilter, Search, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { useEvolution } from "@/components/demo/evolution-provider";
import { EvidenceBadge } from "@/components/evidence/evidence-badge";
import { EvidenceUpgradePath } from "@/components/evidence/evidence-upgrade-path";
import { DecisionProvenanceDrawer } from "@/components/evidence/decision-provenance-drawer";
import { EvidenceLevel, FitnessDimensionKey } from "@/domain/types";

export default function OpportunitiesPage() {
  const { state, currentVersion, selectedOpportunity, selectOpportunity, addToValidationPool, rejectOpportunity, generateConcept } = useEvolution();
  const [query, setQuery] = useState("");
  const [level, setLevel] = useState<"all" | EvidenceLevel>("all");
  const [dataType, setDataType] = useState("all");
  const [view, setView] = useState<"active" | "failed">("active");
  const [metric, setMetric] = useState<FitnessDimensionKey | null>(null);
  const visibleEvidence = useMemo(() => state.evidence.filter((item) => {
    const matchesQuery = `${item.id}${item.excerpt}${item.persona}${item.scenario}${item.painPoint}`.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (level === "all" || item.level === level) && (dataType === "all" || item.dataType === dataType);
  }), [state.evidence, query, level, dataType]);
  const visibleOpportunities = state.opportunities.filter((item) => view === "failed" ? item.status === "rejected" : item.status !== "rejected");
  const linkedEvidence = state.evidence.filter((item) => selectedOpportunity.evidenceIds.includes(item.id));

  return <div className="page-frame"><div className="page-heading"><div><p className="section-kicker">Opportunity Evidence Workbench</p><h1 className="section-title">需求机会</h1><p className="page-description">从消费信号、证据等级和反向证据出发，形成可验证的产品机会。</p></div><div className="segmented"><button onClick={() => setView("active")} className={view === "active" ? "active" : ""}>活跃机会</button><button onClick={() => setView("failed")} className={view === "failed" ? "active" : ""}>失败谱系</button></div></div>

    <div className="opportunity-layout">
      <aside className="workbench-panel"><PanelTitle icon={ListFilter} title="消费信号库" count={visibleEvidence.length} /><div className="space-y-2 border-b border-[#E1E6E3] p-3"><label className="search-field"><Search className="h-4 w-4" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索证据、人群、场景…" aria-label="搜索消费信号" /></label><div className="grid grid-cols-2 gap-2"><select value={level} onChange={(event) => setLevel(event.target.value as "all" | EvidenceLevel)} aria-label="证据等级筛选"><option value="all">全部等级</option><option value="A">A级</option><option value="B">B级</option><option value="C">C级</option><option value="D">D级</option></select><select value={dataType} onChange={(event) => setDataType(event.target.value)} aria-label="数据类型筛选"><option value="all">全部数据</option><option value="humanResearch">真人研究</option><option value="publicEvidence">公开证据</option><option value="syntheticSimulation">模拟演示</option></select></div></div><div className="max-h-[calc(100vh-300px)] space-y-2 overflow-y-auto p-3">{visibleEvidence.map((item) => <article key={item.id} className={`signal-card ${selectedOpportunity.evidenceIds.includes(item.id) ? "signal-card-linked" : ""}`}><div className="flex items-center justify-between gap-2"><span className="font-mono text-[11px] font-semibold text-[#52625B]">{item.id}</span><EvidenceBadge level={item.level} compact /></div><p className="mt-2 text-xs font-medium leading-5 text-[#2D3436]">{item.excerpt}</p><div className="mt-2 flex flex-wrap gap-1"><span className="meta-chip">{item.platform}</span><span className="meta-chip">{item.scenario}</span>{item.isHuman ? <span className="meta-chip meta-human"><UserRound className="h-3 w-3" />真人</span> : null}{item.dataType === "syntheticSimulation" ? <span className="simulation-mini">AI预筛</span> : null}</div>{item.sourceUrl && item.dataType !== "syntheticSimulation" ? <a href={item.sourceUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-[11px] font-medium text-[#5B8C5A]">查看来源<ExternalLink className="h-3 w-3" /></a> : null}</article>)}</div></aside>

      <section className="workbench-panel"><PanelTitle icon={Grid2X2} title={view === "active" ? "AI需求聚类" : "失败机会"} count={visibleOpportunities.length} /><div className="border-b border-[#E1E6E3] px-4 py-3"><div className="flex items-center gap-2 text-xs text-[#636E72]"><Filter className="h-3.5 w-3.5" />卡片视图 · 证据矩阵已映射到左侧信号</div></div><div className="max-h-[calc(100vh-260px)] space-y-3 overflow-y-auto p-4">{visibleOpportunities.length === 0 ? <div className="empty-state"><GitBranch className="h-9 w-9" /><p>暂无失败机会。可在右侧人工否决后查看谱系。</p></div> : visibleOpportunities.map((opportunity) => <button key={opportunity.id} onClick={() => selectOpportunity(opportunity.id)} className={`opportunity-card ${selectedOpportunity.id === opportunity.id ? "opportunity-card-active" : ""}`}><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="font-mono text-xs font-semibold text-[#52625B]">{opportunity.id}</span><EvidenceBadge level={opportunity.evidenceLevel} compact /></div><span className={`status-text status-${opportunity.status}`}>{opportunity.status === "validation" ? "真人验证" : opportunity.status === "concept" ? "已生成物种" : opportunity.status === "rejected" ? "已否决" : "活跃"}</span></div><h2 className="mt-3 text-left text-lg font-semibold text-[#2D3436]">{opportunity.name}</h2><p className="mt-2 line-clamp-2 text-left text-xs leading-5 text-[#636E72]">{opportunity.jtbd}</p><div className="mt-4 grid grid-cols-3 gap-2"><Mini label="证据" value={String(opportunity.evidenceIds.length)} /><Mini label="复核" value={`${opportunity.humanReviewRate}%`} /><Mini label="Fitness" value={String(opportunity.fitness)} /></div><div className="mt-3 flex flex-wrap gap-1"><span className="meta-chip">{opportunity.persona}</span><span className="meta-chip">{opportunity.scenario}</span></div></button>)}</div></section>

      <aside className="workbench-panel detail-panel"><div className="border-b border-[#E1E6E3] p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><EvidenceBadge level={selectedOpportunity.evidenceLevel} /><span className="font-mono text-xs text-[#7D8B85]">{selectedOpportunity.id}</span></div><button onClick={() => setMetric("demand")} className="score-button" aria-label="查看适应度证据链"><span>{selectedOpportunity.fitness}</span> Fitness</button></div><h2 className="mt-4 text-2xl font-semibold text-[#26312D]">{selectedOpportunity.name}</h2><p className="mt-2 text-xs text-[#636E72]">AI置信度 {selectedOpportunity.aiConfidence}% · 人工复核率 {selectedOpportunity.humanReviewRate}% · 覆盖率 {selectedOpportunity.evidenceCoverage}%</p></div><div className="max-h-[calc(100vh-265px)] space-y-5 overflow-y-auto p-5"><Detail label="目标人群" value={selectedOpportunity.persona} /><Detail label="核心场景" value={selectedOpportunity.scenario} /><Detail label="JTBD" value={selectedOpportunity.jtbd} /><Detail label="核心痛点" value={selectedOpportunity.painPoint} /><Detail label="当前替代方案" value={selectedOpportunity.alternative} /><Detail label="产品假设" value={selectedOpportunity.hypothesis} />
        <section className="counter-evidence"><div className="mb-3 flex items-center gap-2"><AlertTriangle className="h-4 w-4" /><h3 className="text-sm font-semibold">反向证据</h3></div>{selectedOpportunity.counterEvidence.map((counter) => <div key={counter.id} className="border-t border-[#E9C9C5] py-3 first:border-0 first:pt-0"><p className="text-xs font-medium text-[#7A3E3E]">{counter.statement}</p><dl className="mt-2 grid gap-1 text-[11px] text-[#805D5D]"><div><dt>替代方案</dt><dd>{counter.alternative}</dd></div><div><dt>不购买原因</dt><dd>{counter.nonPurchaseReason}</dd></div><div><dt>高风险假设</dt><dd>{counter.riskyAssumption}</dd></div></dl></div>)}</section>
        <EvidenceUpgradePath level={selectedOpportunity.evidenceLevel} completed={1} />
        <section><h3 className="mb-2 text-sm font-semibold">五门预审</h3><div className="grid grid-cols-5 gap-1">{selectedOpportunity.gatePreview.map((status, index) => <div key={index} className={`gate-mini gate-${status.toLowerCase()}`}><span>V{index + 1}</span><b>{status}</b></div>)}</div></section>
        <div className="grid grid-cols-2 gap-2"><button onClick={() => addToValidationPool(selectedOpportunity.id)} className="secondary-action justify-center"><CheckCircle2 className="h-4 w-4" />{selectedOpportunity.validationPool ? "移出验证池" : "加入真人验证池"}</button><button onClick={() => generateConcept(selectedOpportunity.id)} className="primary-action justify-center"><Sparkles className="h-4 w-4" />生成产品概念</button><button onClick={() => rejectOpportunity(selectedOpportunity.id)} className="danger-action justify-center"><Ban className="h-4 w-4" />否决机会</button><Link href="/evolution" className="secondary-action justify-center"><GitBranch className="h-4 w-4" />查看失败谱系</Link></div>
      </div></aside>
    </div>
    <DecisionProvenanceDrawer open={metric !== null} onClose={() => setMetric(null)} metric={metric ?? "demand"} score={currentVersion.fitness.dimensions[metric ?? "demand"]} evidence={linkedEvidence} fitness={currentVersion.fitness} />
  </div>;
}

function PanelTitle({ icon: Icon, title, count }: { icon: React.ElementType; title: string; count: number }) { return <div className="flex h-14 items-center justify-between border-b border-[#E1E6E3] px-4"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-[#5B8C5A]" /><h2 className="text-sm font-semibold">{title}</h2></div><span className="count-chip">{count}</span></div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-[#F3F5F3] p-2 text-left"><p className="text-[10px] text-[#7D8B85]">{label}</p><p className="mt-0.5 text-sm font-semibold text-[#315C46]">{value}</p></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <section><p className="text-[11px] font-semibold uppercase tracking-[0.12em] text-[#7D8B85]">{label}</p><p className="mt-1.5 text-sm leading-6 text-[#37423E]">{value}</p></section>; }
