"use client";

import Link from "next/link";
import { ArrowRight, Beaker, CheckCircle2, MinusCircle, StopCircle } from "lucide-react";
import { useDecision } from "@/components/decision/decision-provider";
import { DataBoundary, EmptyState, WorkspaceHeading } from "@/components/decision/workspace-ui";

export default function TestsPage(){const {state}=useDecision();const test=state.tests[0];return <div className="page-frame"><WorkspaceHeading eyebrow="Next-Best-Test" title="下一项验证" description="一次只验证一个主变量。系统说明为什么现在先做这项测试、最低成本是多少，以及什么结果允许继续、必须补证或应当停止。"/><DataBoundary/>{!test?<EmptyState title="尚不能推荐实验" body="没有项目、证据和关键假设时，系统不会凭空生成验证方案。"/>:<div className="test-layout" data-guide="test"><section className="test-protocol"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="simulation-chip">{test.id} · {test.isDigital?"数字实验":"真人概念验证"}</span><h2 className="mt-4 text-2xl font-semibold">{test.hypothesis}</h2></div><Beaker className="h-8 w-8 text-[#5B8C5A]"/></div><div className="mt-7 grid gap-4 md:grid-cols-2"><Protocol label="唯一主变量" value={test.primaryVariable}/><Protocol label="基准组" value={test.baseline}/><Protocol label="预算" value={`¥${test.budget.toLocaleString("zh-CN")}`}/><Protocol label="周期与样本" value={`${test.duration} · ${test.sample}`}/></div><div className="mt-6"><p className="field-label">控制条件</p><div className="mt-3 flex flex-wrap gap-2">{test.controls.map(item=><span key={item} className="control-chip">{item}</span>)}</div></div><div className="threshold-grid mt-7"><Threshold icon={CheckCircle2} tone="pass" title="通过" body={test.passThreshold}/><Threshold icon={MinusCircle} tone="supplement" title="补证" body={test.supplementThreshold}/><Threshold icon={StopCircle} tone="stop" title="停止" body={test.stopThreshold}/></div></section><aside className="space-y-5"><section className="panel-surface"><p className="section-kicker">Information gain</p><h2 className="mt-2 text-xl font-semibold">为什么现在先做它</h2><p className="mt-4 text-sm leading-6 text-[#65726B]">它用约{Math.round(test.budget/(state.project.nextInvestmentAmount||test.budget)*100)}%的下一笔投入，先验证最危险的价格与组织方式假设；结果将直接改变是否支付包装打样费。</p></section><section className="panel-surface"><p className="section-kicker">Experiment ledger</p><h2 className="mt-2 text-xl font-semibold">实验类型分开计数</h2><div className="mt-4 space-y-3"><Count label="数字实验" value={test.isDigital?1:0} note="情景与规则测试"/><Count label="真人校准" value={test.isDigital?0:1} note="目标用户验证"/><Count label="样品验证" value={0} note="待回填"/><Count label="销售结果" value={0} note="待回填"/></div><p className="data-caution">不得通过刷新随机结果、改写文案或重复运行来凑满“100次”。</p></section><Link href="/decision" className="primary-action w-full">生成投前决策单<ArrowRight className="h-4 w-4"/></Link></aside></div>}</div>}
function Protocol({label,value}:{label:string;value:string}){return <div className="protocol-field"><span>{label}</span><strong>{value}</strong></div>}
function Threshold({icon:Icon,tone,title,body}:{icon:typeof CheckCircle2;tone:string;title:string;body:string}){return <article className={`threshold-card ${tone}`}><Icon className="h-5 w-5"/><strong>{title}</strong><p>{body}</p></article>}
function Count({label,value,note}:{label:string;value:number;note:string}){return <div className="count-row"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
