import Link from "next/link";
import { AlertTriangle, ArchiveRestore, ArrowRight, Building2, Database, FileInput, FolderLock, PackageCheck, ShieldAlert } from "lucide-react";

const issueUrl="https://github.com/sufangfang0123-svg/syy-ai-wb/issues/new?template=enterprise-pilot.yml";

export default function PilotPage(){return <div>
  <section className="delivery-hero"><div className="page-frame py-14 md:py-20"><span className="enterprise-preview-badge">v0.4.0 · 单企业本地封闭试点</span><p className="section-kicker mt-6">Enterprise pilot delivery</p><h1>在企业控制的本机环境中，<span>跑通一次可追溯新品投前决策。</span></h1><p>适用于正在准备下一笔打样、备货、投放或渠道费用，且愿意由负责人核验来源、关系、阈值和最终决定的单一企业团队。</p><div className="mt-8 flex flex-wrap gap-3"><a href={issueUrl} target="_blank" rel="noopener noreferrer" className="primary-action px-5 py-3">提交试点申请<ArrowRight className="h-4 w-4" /></a><Link href="/enterprise-demo" className="secondary-action px-5 py-3">查看企业闭环演示</Link><Link href="/proof" className="secondary-action px-5 py-3">查看系统验收证明</Link></div><p className="mt-4 text-xs leading-6 text-[#6D7973]">公开Issue不得提交商业机密、个人信息、未脱敏附件、Token或企业内部URL。</p></div></section>

  <section className="page-frame delivery-section"><div className="delivery-heading"><p className="section-kicker">Fit</p><h2>适用对象与决策场景</h2></div><div className="delivery-grid three"><PilotCard icon={Building2} title="适用对象" items={["消费新品负责人","产品与商品负责人","中小企业经营者","供应链、质量与合规协作人"]}/><PilotCard icon={PackageCheck} title="适用决策" items={["是否进入下一轮打样","是否开模或备货","是否追加渠道或投放费用","当前应继续、补证还是停止"]}/><PilotCard icon={FileInput} title="企业需准备" items={["明确的下一笔投入问题","已授权且可核验的内部材料","公开且允许访问的URL","验证预算、阈值与责任人自我声明"]}/></div></section>

  <section className="border-y border-[#DFE6E9] bg-white/60"><div className="page-frame delivery-section"><div className="delivery-heading"><p className="section-kicker">Install</p><h2>本地安装与启动</h2><p>Windows首次运行需要Node.js、Python与Git；应用和数据均留在企业控制的设备中。</p></div><pre className="command-block"><code>{`git clone https://github.com/sufangfang0123-svg/syy-ai-wb.git\ncd syy-ai-wb\nnpm.cmd ci\nnpm.cmd run setup:integrated\nnpm.cmd run dev:integrated`}</code></pre><p className="mt-4 text-sm leading-7 text-[#5F6D66]">打开 <code>http://127.0.0.1:3000/real/</code>；后端健康检查为 <code>http://127.0.0.1:8000/api/v1/health</code>。后端不健康时真实入口保持关闭，不回退模拟数据。</p></div></section>

  <section className="page-frame delivery-section"><div className="delivery-grid two"><PilotCard icon={Database} title="数据保存位置" items={["默认根目录 backend/data/","SQLite：next-dollar-gate.sqlite3","附件快照：uploads/","可用NDG_DATA_DIR整体改址","附件不会由静态站公开"]}/><PilotCard icon={FolderLock} title="导入边界" items={["粘贴文本与单个公开URL","不超过5MB的txt/md/csv/文本型pdf","URL必须由用户授权且公开可访问","不绕过登录、反爬、付费墙或平台限制","扫描PDF/OCR与社交平台自动抓取不支持"]}/><PilotCard icon={ArchiveRestore} title="备份与恢复" items={["先停止本地服务","同时复制SQLite与uploads目录","记录备份时间与文件SHA-256","恢复时先保留当前目录副本","重启后检查health与项目导出"]}/><PilotCard icon={ShieldAlert} title="数据责任" items={["不得导入无授权敏感信息","企业负责脱敏、保存期限和删除","当前无账号、RBAC或可信身份审计","decided_by仅为人工自我声明","规则输出不替代企业审批"]}/></div></section>

  <section className="border-y border-[#DFE6E9] bg-[#F3F1EC]"><div className="page-frame delivery-section"><div className="delivery-heading"><p className="section-kicker">Pilot workflow</p><h2>试点完整流程与交付物</h2></div><ol className="pilot-flow">{["定义项目和下一笔投入","导入材料并人工确认Evidence","建立假设、支持/反驳及证据治理关系","设计阈值化Validation并回填原始结果","执行确定性Gate并记录人工Decision","验证stale、进入下一轮并导出JSON"].map((item,index)=><li key={item}><span>{String(index+1).padStart(2,"0")}</span>{item}</li>)}</ol><div className="delivery-grid two mt-8"><PilotCard icon={PackageCheck} title="预期交付物" items={["本地可运行的单企业项目空间","Evidence—Assumption—Validation追溯链","五维Gate快照与人工Decision记录","历史版本、stale状态和审计事件","脱敏JSON导出与备份说明"]}/><PilotCard icon={AlertTriangle} title="本版不提供" items={["云部署、多租户、账号或RBAC","企业审批流和可信身份审计","全网采集、平台爬虫或私域连接","真实AI分析、销量、ROI或成功率预测","自动生产、投资、合规或经营决定"]}/></div></div></section>

  <section className="page-frame"><div className="delivery-cta"><div><p className="section-kicker">Pilot request</p><h2>以脱敏问题描述申请本地试点</h2><p>Issue仅用于确认品类、下一笔决策场景、计划时间与技术环境。商业机密和真实材料需通过双方另行确认的安全渠道处理。</p></div><a href={issueUrl} target="_blank" rel="noopener noreferrer" className="primary-action px-5 py-3">打开试点申请模板<ArrowRight className="h-4 w-4" /></a></div></section>
</div>}

function PilotCard({icon:Icon,title,items}:{icon:typeof Building2;title:string;items:string[]}){return <article className="delivery-card"><Icon/><h3>{title}</h3><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></article>}
