"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertOctagon, ArrowRight, Check, ChevronRight, Dna, GitBranch, Lock, LockOpen, RotateCw, ShieldAlert, Sparkles, X } from "lucide-react";
import { useEvolution } from "@/components/demo/evolution-provider";
import { DecisionProvenanceDrawer } from "@/components/evidence/decision-provenance-drawer";
import { EvidenceBadge } from "@/components/evidence/evidence-badge";
import { FitnessRing } from "@/components/evolution/fitness-ring";
import { FITNESS_LABELS, GENOME_LABELS } from "@/domain/constants";
import { FitnessDimensionKey, GateStatus, GenomeCategory, ProductVersion } from "@/domain/types";

const categories = Object.keys(GENOME_LABELS) as GenomeCategory[];
const impactPresets = [
  { id: "compact", category: "G5" as const, valueId: "g5-3", label: "小体积包装", impacts: { demand: 3, differentiation: 3, communication: 4, commercial: -2, supply: -3 } },
  { id: "one-hand", category: "G5" as const, valueId: "g5-2", label: "强化单手取用", impacts: { pain: 4, differentiation: 2, communication: 2, supply: -1 } },
  { id: "refill", category: "G8" as const, valueId: "g8-2", label: "增加补充装", impacts: { brand: 2, commercial: 3, supply: -2, compliance: 1 } },
];

export default function EvolutionPage() {
  const { state, currentVersion, toggleGenomeValue, toggleGenomeLock, createMutation, setGateStatus } = useEvolution();
  const [activeVersionId, setActiveVersionId] = useState(currentVersion.id);
  const [metric, setMetric] = useState<FitnessDimensionKey | null>(null);
  const [mutationId, setMutationId] = useState(impactPresets[0].id);
  const [price, setPrice] = useState(79);
  const [treeNode, setTreeNode] = useState<ProductVersion | null>(null);
  const displayedVersion = state.versions.find((item) => item.id === activeVersionId) ?? currentVersion;
  const selectedMutation = impactPresets.find((item) => item.id === mutationId) ?? impactPresets[0];
  const evidence = state.evidence.filter((item) => displayedVersion.fitness.evidenceIds.includes(item.id));
  const hardFail = state.gates.some((gate) => gate.mode === "hard" && gate.status === "FAIL");
  const timeline = state.versions.filter((item) => item.opportunityId === "OP-01");

  const priceImpact = useMemo(() => price <= 59 ? { demand: 3, commercial: -5 } : price >= 99 ? { demand: -5, commercial: 3 } : { demand: 0, commercial: 0 }, [price]);
  const combinedImpacts = { ...selectedMutation.impacts, demand: (selectedMutation.impacts.demand ?? 0) + priceImpact.demand, commercial: (selectedMutation.impacts.commercial ?? 0) + priceImpact.commercial };

  useEffect(() => setActiveVersionId(currentVersion.id), [currentVersion.id]);

  const create = () => {
    createMutation({ category: selectedMutation.category, valueId: selectedMutation.valueId, label: `${selectedMutation.label} · 价格${price}元`, impacts: combinedImpacts });
  };

  return <div className="page-frame"><div className="page-heading"><div><p className="section-kicker">Evolution Laboratory</p><h1 className="section-title">产品进化</h1><p className="page-description">让产品物种在证据约束下变异、竞争、淘汰和校准。</p></div><div className="flex items-center gap-2"><span className="simulation-chip">D级模拟 · 仅用于预筛</span><EvidenceBadge level={displayedVersion.evidenceLevel} /></div></div>

    <section className="evolution-timeline"><div className="mb-5 flex items-center justify-between"><div><p className="section-kicker">Evolution Timeline</p><h2 className="text-xl font-semibold">版本谱系</h2></div><p className="text-xs text-[#636E72]">点击版本切换工作台</p></div><div className="timeline-row">{timeline.map((version, index) => <div key={version.id} className="contents"><button onClick={() => setActiveVersionId(version.id)} className={`version-node version-${version.status} ${displayedVersion.id === version.id ? "version-node-active" : ""}`}><span className="version-dot">{version.status === "survivor" ? <Check className="h-3 w-3" /> : version.status === "eliminated" ? <X className="h-3 w-3" /> : <RotateCw className="h-3 w-3" />}</span><b>{version.label}</b><small>{version.fitness.finalFitness} Fitness</small><span>{version.mutation}</span></button>{index < timeline.length - 1 ? <ChevronRight className="h-5 w-5 shrink-0 text-[#A7B1AD]" /> : null}</div>)}</div></section>

    <div className="mt-6 grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><section className="data-surface rounded-[24px] p-6"><div className="flex items-start justify-between"><div><p className="section-kicker">Fitness Dashboard</p><h2 className="text-xl font-semibold">{displayedVersion.name} {displayedVersion.label}</h2><p className="mt-1 text-xs text-[#636E72]">{hardFail ? "Hard Gate失败：状态直接REJECTED" : displayedVersion.status === "survivor" ? "当前幸存物种" : displayedVersion.status === "eliminated" ? "已进入失败谱系" : "实验中"}</p></div><button onClick={() => setMetric("demand")} aria-label="展开适应度证据链"><FitnessRing value={displayedVersion.fitness.finalFitness} size={126} /></button></div><div className="formula-grid"><Formula label="Raw Fitness" value={displayedVersion.fitness.rawFitness} /><span>×</span><Formula label="Evidence Factor" value={displayedVersion.fitness.evidenceFactor.toFixed(2)} /><span>−</span><Formula label="Risk Penalty" value={displayedVersion.fitness.riskPenalty} /><span>=</span><Formula label="Final Fitness" value={displayedVersion.fitness.finalFitness} strong /></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{(Object.entries(displayedVersion.fitness.dimensions) as [FitnessDimensionKey, number][]).map(([key, value]) => <button key={key} onClick={() => setMetric(key)} className="fitness-metric"><span>{FITNESS_LABELS[key]}</span><b>{value}</b><i style={{ width: `${value}%` }} /></button>)}</div><p className="mt-4 rounded-lg bg-[#F3F1EC] p-3 text-xs leading-5 text-[#636E72]">Final Fitness = Raw Fitness × Evidence Factor − Risk Penalty。任何 Hard Gate = FAIL 时停止评分并直接淘汰。</p></section>

      <section className="evolution-surface rounded-[24px] p-6"><div className="flex items-start justify-between"><div><p className="section-kicker text-[#A8D5BA]">Mutation Simulator</p><h2 className="text-xl font-semibold text-white">运行一次基因变异</h2></div><span className="simulation-chip border-white/15 bg-white/10 text-white">D级模拟</span></div><div className="mt-5 grid gap-5 md:grid-cols-[.8fr_1.2fr]"><div><label className="field-label">变异方案</label><div className="space-y-2">{impactPresets.map((preset) => <button key={preset.id} onClick={() => setMutationId(preset.id)} className={`mutation-option ${mutationId === preset.id ? "mutation-option-active" : ""}`}><Sparkles className="h-4 w-4" />{preset.label}</button>)}</div><label className="field-label mt-5">价格情景：{price}元</label><input type="range" min="49" max="109" step="10" value={price} onChange={(event) => setPrice(Number(event.target.value))} className="w-full accent-[#A8D5BA]" aria-label="价格情景" /><div className="mt-1 flex justify-between text-[10px] text-white/45"><span>谨慎 49</span><span>基准 79</span><span>进取 109</span></div></div><div><p className="field-label">Mutation Impact Matrix</p><div className="grid grid-cols-2 gap-2">{(Object.entries(combinedImpacts) as [FitnessDimensionKey, number][]).map(([key, value]) => <div key={key} className="impact-cell"><span>{FITNESS_LABELS[key]}</span><b className={value >= 0 ? "text-[#A8D5BA]" : "text-[#F0A9A4]"}>{value >= 0 ? "+" : ""}{value}</b></div>)}</div><button onClick={create} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-[#A8D5BA] px-4 py-3 text-sm font-semibold text-[#244936] hover:bg-[#BCE2C9]"><Dna className="h-4 w-4" />创建下一代版本<ArrowRight className="h-4 w-4" /></button></div></div></section></div>

    <section className="mt-6 rounded-[24px] border border-[#DFE6E9] bg-white p-6"><div className="mb-5"><p className="section-kicker">Genome Workbench</p><h2 className="text-xl font-semibold">八类棉基因</h2><p className="mt-1 text-xs text-[#636E72]">选择基因会改变当前版本；锁定后变异操作不会覆盖该值。</p></div><div className="genome-grid">{categories.map((category) => <article key={category} className="genome-card"><div className="mb-3 flex items-start justify-between"><div><span className="font-mono text-xs font-bold text-[#5B8C5A]">{category}</span><h3 className="text-sm font-semibold">{GENOME_LABELS[category].title}</h3></div><Dna className="h-4 w-4 text-[#9CAB9F]" /></div><p className="mb-3 text-[10px] text-[#7D8B85]">{GENOME_LABELS[category].subtitle}</p><div className="space-y-1.5">{displayedVersion.genome[category].map((value) => <div key={value.id} className={`genome-value ${value.selected ? "genome-value-selected" : ""}`}><button onClick={() => toggleGenomeValue(category, value.id)} disabled={displayedVersion.id !== currentVersion.id || value.locked} className="flex min-w-0 flex-1 items-center gap-2 text-left disabled:cursor-not-allowed"><span className="gene-check">{value.selected ? <Check className="h-3 w-3" /> : null}</span><span className="truncate">{value.label}</span>{!value.verified ? <em>待确认</em> : null}</button><button onClick={() => toggleGenomeLock(category, value.id)} disabled={displayedVersion.id !== currentVersion.id} className="p-1 text-[#7D8B85] disabled:opacity-30" aria-label={`${value.locked ? "解锁" : "锁定"}${value.label}`}>{value.locked ? <Lock className="h-3.5 w-3.5" /> : <LockOpen className="h-3.5 w-3.5" />}</button></div>)}</div></article>)}</div></section>

    <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_1fr]"><section className="rounded-[24px] border border-[#DFE6E9] bg-white p-6"><div className="mb-5 flex items-center justify-between"><div><p className="section-kicker">Five Decision Gates</p><h2 className="text-xl font-semibold">五道否决</h2></div>{hardFail ? <span className="status-badge status-fail"><AlertOctagon className="h-3.5 w-3.5" />REJECTED</span> : <span className="status-badge status-warning"><ShieldAlert className="h-3.5 w-3.5" />HUMAN REVIEW</span>}</div><div className="space-y-3">{state.gates.map((gate) => <article key={gate.id} className={`gate-card gate-card-${gate.status.toLowerCase()}`}><div className="flex flex-wrap items-center gap-3"><span className="gate-code">{gate.id}</span><div className="min-w-[140px] flex-1"><div className="flex items-center gap-2"><h3 className="text-sm font-semibold">{gate.name}</h3><span className={`mode-chip mode-${gate.mode}`}>{gate.mode === "hard" ? "Hard Gate" : "Soft Gate"}</span></div><p className="mt-1 text-[11px] text-[#636E72]">{gate.reason}</p></div><div className="segmented segmented-small">{(["PASS", "WARNING", "FAIL"] as GateStatus[]).map((status) => <button key={status} onClick={() => setGateStatus(gate.id, status)} className={gate.status === status ? "active" : ""}>{status}</button>)}</div></div><div className="mt-2 grid gap-1 text-[10px] text-[#7D8B85] sm:grid-cols-2"><p>AI：{gate.aiRole}</p><p>最终责任人：{gate.owner}</p></div></article>)}</div></section>

      <section className="rounded-[24px] border border-[#DFE6E9] bg-[#F3F1EC] p-6"><div className="mb-5"><p className="section-kicker">Evolution Tree</p><h2 className="text-xl font-semibold">失败谱系</h2><p className="mt-1 text-xs text-[#636E72]">失败不是垃圾数据，而是企业知识资产。</p></div><div className="tree-root"><span>Opportunity OP-01</span><div className="tree-branches">{timeline.map((version) => <button key={version.id} onClick={() => setTreeNode(version)} className={`tree-node tree-${version.status}`}><GitBranch className="h-4 w-4" /><div><b>{version.label}</b><small>{version.mutation}</small></div></button>)}</div></div>{treeNode ? <div className="mt-5 rounded-xl border border-[#D8DFDB] bg-white p-4"><div className="flex items-center justify-between"><div><span className="font-mono text-xs text-[#7D8B85]">{treeNode.id}</span><h3 className="text-base font-semibold">{treeNode.name} {treeNode.label}</h3></div><button onClick={() => setTreeNode(null)} className="icon-button"><X className="h-4 w-4" /></button></div><dl className="tree-detail"><div><dt>状态</dt><dd>{treeNode.status}</dd></div><div><dt>淘汰Gate</dt><dd>{treeNode.eliminatedBy ?? "未淘汰"}</dd></div><div><dt>关键学习</dt><dd>{treeNode.learning ?? "验证进行中"}</dd></div><div><dt>未来复活</dt><dd>{treeNode.revivable ? "允许，需补充新证据" : "不允许"}</dd></div></dl></div> : null}</section></div>

    <DecisionProvenanceDrawer open={metric !== null} onClose={() => setMetric(null)} metric={metric ?? "demand"} score={displayedVersion.fitness.dimensions[metric ?? "demand"]} evidence={evidence} fitness={displayedVersion.fitness} />
  </div>;
}

function Formula({ label, value, strong = false }: { label: string; value: string | number; strong?: boolean }) { return <div className={`formula-card ${strong ? "formula-strong" : ""}`}><span>{label}</span><b>{value}</b></div>; }
