"use client";

import Link from "next/link";
import { ArrowRight, Banknote, CheckCircle2, ClipboardCheck, FileSearch, FlaskConical, Network, PackageCheck, ShieldAlert, Users } from "lucide-react";
import { useDecision } from "@/components/decision/decision-provider";

const mechanism = [
  [Banknote, "说清下一笔投入", "打样、开模、备货、推广或下一道Gate资源。"],
  [FileSearch, "核对证据", "来源、样本、适用范围、冲突和限制全部可追溯。"],
  [Network, "找到危险假设", "同时看错误代价和证据缺口，而不是只看热度。"],
  [FlaskConical, "推荐最低成本验证", "一次只验证一个主变量，并预设通过、补证和停止阈值。"],
  [ClipboardCheck, "形成投前决策单", "系统建议与人工决定分开记录，结果继续回流校准。"],
] as const;

export default function ProductSite() {
  const { state } = useDecision();
  const project = state.project;
  const decision = state.decision;
  return <div>
    <section className="hero-section"><div className="mx-auto grid max-w-[1500px] items-center gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-10 lg:py-28"><div><p className="section-kicker">Evolution Lab · Next-Dollar Gate</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[1.05] tracking-[-0.045em] text-[#26312D] md:text-7xl">先别急着做新品。<span className="mt-3 block text-[#315C46]">先判断下一笔钱值不值得花。</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#627169]">在支付打样费、开模费、备货费或推广费之前，识别当前最危险的假设，判断证据是否足够，并推荐成本最低、最能改变决策的下一项验证。</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/workspace" className="primary-action px-5 py-3">创建投前决策项目<ArrowRight className="h-4 w-4" /></Link><a href="#case" className="secondary-action px-5 py-3">查看棉品案例</a></div><p className="mt-4 text-xs text-[#7A867F]">AI提供决策支持，不替代负责人、真人研究、样品测试或合规审核。</p></div><div className="decision-hero-card"><div className="flex items-center justify-between gap-3"><span className="simulation-chip">模拟案例 · {project.id}</span><span className="decision-status supplement">先补证</span></div><p className="mt-7 text-xs font-bold uppercase tracking-[.16em] text-white/50">Next investment</p><h2 className="mt-2 text-2xl font-semibold text-white">{project.nextAction}</h2><p className="mt-2 text-5xl font-semibold text-[#C6E2CE]">¥{project.nextInvestmentAmount?.toLocaleString("zh-CN")}</p><div className="mt-7 border-t border-white/10 pt-5"><p className="text-xs text-white/55">当前最危险假设</p><p className="mt-2 text-sm leading-6 text-white">{state.assumptions[0].statement}</p></div><div className="mt-5 rounded-xl bg-white/8 p-4"><p className="text-xs text-white/55">建议先投入</p><p className="mt-1 text-xl font-semibold text-white">¥{state.tests[0].budget.toLocaleString("zh-CN")} · {state.tests[0].duration}</p><p className="mt-2 text-xs leading-5 text-white/60">{decision.confidenceLimit}</p></div></div></div></section>

    <section id="mechanism" className="page-frame"><div className="max-w-3xl"><p className="section-kicker">One engine, one decision moment</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">不是生成更多创意，而是决定下一项证据</h2><p className="page-description">快速版、团队版和企业版使用同一核心引擎；差异只在协作深度、权限、审计和系统接入。</p></div><div className="mt-8 grid gap-4 md:grid-cols-5">{mechanism.map(([Icon, title, body], index) => <article key={title} className="mechanism-card"><span>{String(index + 1).padStart(2, "0")}</span><Icon className="mt-8 h-6 w-6 text-[#5B8C5A]" /><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section id="case" className="border-y border-[#DFE6E9] bg-white/60"><div className="page-frame"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-kicker">First industry pack</p><h2 className="mt-3 text-3xl font-semibold">棉生万物·棉品新品验证包</h2><p className="page-description">棉品知识、Claim边界、成本变量和实验模板作为首个行业配置存在，不写死在通用引擎中。</p></div><span className="simulation-chip">全部为模拟项目数据</span></div><div className="mt-8 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><article className="panel-surface"><p className="section-kicker">Shared fact chain</p><h3 className="mt-2 text-xl font-semibold">{project.name}</h3><div className="mt-6 space-y-3">{[["项目ID",project.id],["下一笔投入",`${project.nextAction} · ¥${project.nextInvestmentAmount?.toLocaleString("zh-CN")}`],["关键证据",decision.evidenceIds.join("、")],["下一验证",`${state.tests[0].id} · ${state.tests[0].primaryVariable}`],["Gate结论","先补证；等待负责人确认"]].map(([label,value])=><div key={label} className="fact-row"><span>{label}</span><strong>{value}</strong></div>)}</div></article><article className="panel-surface"><p className="section-kicker">Validation boundary</p><h3 className="mt-2 text-xl font-semibold">四类结果严格分开</h3><div className="mt-5 grid grid-cols-2 gap-3">{[["数字实验","1项协议","D级只找反例"],["真人校准","0次完成","待执行"],["样品验证","0次完成","待回填"],["销售结果","0次回填","待回填"]].map(([title,value,note])=><div key={title} className="validation-count"><span>{title}</span><strong>{value}</strong><small>{note}</small></div>)}</div><div className="data-caution"><ShieldAlert className="h-4 w-4" />“数字世界上市100次”指可审计、可复现的情景实验协议，不等于100次真人测试、样品生产或真实上市。</div></article></div></div></section>

    <section id="versions" className="page-frame"><div className="text-center"><p className="section-kicker">One engine, three depths</p><h2 className="mt-3 text-3xl font-semibold">同一决策闭环，按组织深度使用</h2></div><div className="mx-auto mt-8 grid max-w-5xl gap-5 md:grid-cols-3"><VersionCard icon={PackageCheck} title="快速版" audience="小微品牌、卖家、创业团队" items={["四问式建项","一个危险假设","一个最低成本测试","一张投前决策单"]} billing="按次、按项目或轻量订阅" /><VersionCard icon={Users} title="团队版" audience="成长型品牌、ODM/OEM团队" items={["多成员协作","实验与审批账本","真人/样品/销售回填","失败复用"]} billing="月度或年度订阅" /><VersionCard icon={CheckCircle2} title="企业版" audience="成熟研发与创新组织" items={["角色权限与审计","企业规则与自定义Gate","API与既有系统对接","项目组合视图"]} billing="企业年费＋实施与行业包" /></div><div className="mt-10 text-center"><Link href="/workspace" className="primary-action px-6 py-3">进入企业工作台<ArrowRight className="h-4 w-4" /></Link></div></section>
  </div>;
}

function VersionCard({ icon: Icon, title, audience, items, billing }: { icon: typeof Users; title: string; audience: string; items: string[]; billing: string }) { return <article className="version-card"><Icon className="h-6 w-6 text-[#5B8C5A]" /><h3>{title}</h3><p>{audience}</p><ul>{items.map((item)=><li key={item}><CheckCircle2 className="h-4 w-4" />{item}</li>)}</ul><small>{billing}</small></article>; }
