"use client";

import Link from "next/link";
import { useRef, useState } from "react";
import { AlertTriangle, ArrowRight, CheckCircle2, Database, Download, FileInput, LoaderCircle, RefreshCw, ShieldCheck } from "lucide-react";
import { useProductWorkbench } from "@/components/workbench/product-workbench-provider";
import { api } from "@/lib/real-api";
import { AIProposal, ChangeProposal, ContentAsset, ProductConcept, ScenarioCandidate } from "@/lib/local-workbench-adapter";
import { runtimeConfig } from "@/config/runtime";
import { canReviewProposal, categoryPackSelection, feedbackChangeProposal, preflightFeedbackCsv, scenarioPriorityLabel } from "@/lib/workbench-validation";
import { ModeSwitch } from "@/components/decision/workspace-ui";
import { ServiceStatus } from "@/components/system/service-status";

export type LocalStage="overview"|"insights"|"opportunities"|"concept"|"scenarios"|"gate"|"content"|"results"|"decision";
const stageCopy:Record<LocalStage,[string,string,string]>={
  overview:["Local product workspace","真实项目总览","先确认项目、品类包、数据边界、阻断和下一项人工任务。"],
  insights:["Authorized inputs","授权材料与信号收件箱","只保存用户明确授权的材料；Evidence先进入草稿，人工确认和关联后才影响固定Gate。"],
  opportunities:["Human-reviewed proposals","机会与AI建议包","导入结构化AI建议包，校验引用与输入快照；人工接受后才生成正式Opportunity。"],
  concept:["Versioned product concept","产品概念共创","概念字段保留来源、版本和风险；实质修改会把情景、内容与未完成建议标记stale。"],
  scenarios:["4 × 5 × 5 funnel","数字情景筛选","保留100个候选空间，但主流程只显示漏斗；输入缺失时不生成总分。"],
  gate:["Deterministic gate boundary","Evidence → Assumption → Validation → Gate","AI不参与Gate计算，不自动确认Evidence或填写验证结果；固定规则保持NDG_GATE_V0.3.0。"],
  content:["Traceable channel assets","内容中枢与声明检查","每条内容保留概念、产品基因、Evidence、原始/人工版本与审核状态；检查器只提示不批准。"],
  results:["Validated local import","反馈导入与变更提案","反馈CSV先做严格校验，再形成待人工审查的ChangeProposal，不直接修改产品概念。"],
  decision:["Human accountable decision","决策、建议层与下一轮","Gate、推荐层与人工Decision分离；策略和变更必须由人工接受或拒绝。"],
};

function arr(value:string):string[]{try{return JSON.parse(value) as string[];}catch{return[];}}
function obj<T=Record<string,unknown>>(value:string):T{try{return JSON.parse(value) as T;}catch{return {} as T;}}
const statusName:Record<string,string>={candidate:"候选",confirmed:"已确认",rejected:"已拒绝",selected:"已选择",candidate_space:"候选空间",shortlisted:"待复核短名单",must_validate:"首轮必须验证",validation:"已进入Validation",pending:"待审核",approved:"已通过",changes:"需修改",accepted:"已接受",proposed:"待人工审查",superseded:"已替代"};

export function LocalWorkbenchStage({stage}:{stage:LocalStage}){
  const wb=useProductWorkbench();
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[error,setError]=useState("");
  const run=async(action:()=>Promise<unknown>,message:string)=>{setBusy(true);setError("");setNotice("");try{await action();setNotice(message);}catch(reason){setError(reason instanceof Error?reason.message:"操作失败");}finally{setBusy(false);}};
  const copy=stageCopy[stage];
  const boundary = stage==="overview"?<><ServiceStatus/><div className="local-workspace-switch"><ModeSwitch/></div></>:null;
  if(wb.localLoading)return <div className="page-frame">{boundary}<div className="empty-state"><LoaderCircle className="h-8 w-8 animate-spin"/><h1>正在从SQLite恢复工作台</h1><p>不会回退到浏览器夹具。</p></div></div>;
  if(wb.localError)return <div className="page-frame">{boundary}<div className="empty-state"><AlertTriangle className="h-8 w-8"/><h1>本地后端不可用</h1><p>{wb.localError}</p><button className="primary-action" onClick={()=>void wb.refreshLocal()}><RefreshCw className="h-4 w-4"/>重新检查</button></div></div>;
  return <div className="page-frame local-stage-page"><header className="page-heading"><div><p className="section-kicker">{copy[0]}</p><h1>{copy[1]}</h1><p className="page-description">{copy[2]}</p></div>{wb.localBundle?<ProjectPicker/>:null}</header>
    {boundary}
    {notice?<div className="service-status available" role="status"><CheckCircle2 className="h-5 w-5"/><div><strong>已保存到本地数据库</strong><p>{notice}</p></div></div>:null}
    {error?<div className="service-status unavailable" role="alert"><AlertTriangle className="h-5 w-5"/><div><strong>操作未完成</strong><p>{error}</p></div></div>:null}
    {!wb.localBundle?<CreateProject busy={busy} run={run}/>:<StageBody stage={stage} busy={busy} run={run}/>}
  </div>;
}

function ProjectPicker(){const {localProjects,localBundle,selectLocalProject}=useProductWorkbench();return <label className="form-field compact-project-picker"><span>当前真实项目</span><select value={localBundle?.project.id??""} onChange={(event)=>void selectLocalProject(event.target.value)}>{localProjects.map((item)=><option key={item.id} value={item.id}>{item.name} · R{item.revision}</option>)}</select></label>;}

function CreateProject({busy,run}:{busy:boolean;run:(action:()=>Promise<unknown>,message:string)=>Promise<void>}){
  const {createLocalProject}=useProductWorkbench();const [draft,setDraft]=useState({name:"全棉轻适通勤内搭验证",decision_question:"在投入下一笔打样费用前，是否已获得足够证据？",description:"比赛概念方案；非全棉时代正式产品，所有材质、需求和供应结论待确认。",product_category:"有纺服装",target_user:"通勤与叠穿场景人群假设",planned_investment:10000,currency:"CNY"});
  return <section className="panel-surface local-create-project"><p className="section-kicker">First persisted object</p><h2>创建第一个真实项目</h2><p className="data-caution">项目会写入FastAPI/SQLite。页面没有账号系统，负责人字段仅为人工自述；请勿导入敏感或未授权资料。</p><form className="form-grid mt-5" onSubmit={(event)=>{event.preventDefault();void run(()=>createLocalProject(draft),"真实项目已创建并可在刷新后恢复。")}}>{Object.entries(draft).map(([key,value])=><label className="form-field" key={key}><span>{{name:"项目名称",decision_question:"决策问题",description:"边界说明",product_category:"品类",target_user:"目标人群假设",planned_investment:"下一笔计划投入",currency:"币种"}[key]}</span>{key==="description"||key==="decision_question"?<textarea value={String(value)} onChange={(e)=>setDraft({...draft,[key]:e.target.value})}/>:<input type={key==="planned_investment"?"number":"text"} value={value} onChange={(e)=>setDraft({...draft,[key]:key==="planned_investment"?Number(e.target.value):e.target.value})}/>}</label>)}<button disabled={busy} className="primary-action">创建真实项目<ArrowRight className="h-4 w-4"/></button></form></section>;
}

function StageBody({stage,busy,run}:{stage:LocalStage;busy:boolean;run:(action:()=>Promise<unknown>,message:string)=>Promise<void>}){
  if(stage==="overview")return <Overview busy={busy} run={run}/>;
  if(stage==="insights")return <Insights busy={busy} run={run}/>;
  if(stage==="opportunities")return <Opportunities busy={busy} run={run}/>;
  if(stage==="concept")return <Concepts busy={busy} run={run}/>;
  if(stage==="scenarios")return <Scenarios busy={busy} run={run}/>;
  if(stage==="gate")return <GateBoundary/>;
  if(stage==="content")return <Content busy={busy} run={run}/>;
  if(stage==="results")return <Results busy={busy} run={run}/>;
  return <DecisionStage busy={busy} run={run}/>;
}

function Overview({busy,run}:{busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){
  const {localBundle:b,localCategoryPacks,mutateLocal}=useProductWorkbench();if(!b)return null;
  const real=[...b.opportunities,...b.concepts,...b.scenarios,...b.content_assets,...b.feedback_records].filter((x)=>x.data_nature!=="fixed_demo").length,total=b.opportunities.length+b.concepts.length+b.scenarios.length+b.content_assets.length+b.feedback_records.length;
  const risk=b.concepts.find((item)=>item.status==="selected")?.supply_risk||b.concepts.at(-1)?.supply_risk||"尚未创建产品概念，无法判断最高风险";
  return <><section className="overview-kpis"><Kpi label="授权材料" value={String(b.evidence.length)} note={`${b.evidence.filter((x)=>x.status==="confirmed").length}条已人工确认`}/><Kpi label="AI建议" value={String(b.ai_proposals.length)} note={`${b.ai_proposals.filter((x)=>x.status==="proposed").length}条待审；Provider 0次`}/><Kpi label="真实/人工对象" value={total?`${Math.round(real/total*100)}%` : "无数据"} note="不与固定演示汇总"/><Kpi label="revision" value={`R${b.project.revision}`} note={`Round ${b.project.current_round}`}/></section><div className="overview-layout"><section className="panel-surface"><p className="section-kicker">Category Pack</p><h2>{b.category_pack.name} · {b.category_pack.version}</h2><p>{b.category_pack.description}</p><label className="form-field mt-5"><span>切换版本化品类包</span><select defaultValue={b.project.category_pack_id} id="category-pack-select">{localCategoryPacks.map((pack)=><option value={pack.id} key={pack.id}>{pack.name} · {pack.status}</option>)}</select></label><button disabled={busy} className="primary-action mt-4" onClick={()=>{const input=document.getElementById("category-pack-select") as HTMLSelectElement;void run(()=>mutateLocal(`/api/v1/projects/${b.project.id}/category-pack`,"PATCH",categoryPackSelection(input.value,"负责人（人工自述）",b.project.revision)),"品类包已切换；旧Gate/Decision已按revision标记stale。")}}>确认品类包</button></section><aside className="space-y-5"><section className="panel-surface"><p className="section-kicker">Current blocker</p><h2>当前阻断</h2><p>{b.evidence.length?b.assumptions.length?"需把已确认Evidence与关键Assumption建立人工关系并完成Validation。":"尚未创建关键Assumption。":"尚未导入授权Evidence。"}</p></section><section className="panel-surface"><p className="section-kicker">Highest known risk</p><h2>当前最高风险</h2><p>{risk}</p></section><section className="panel-surface"><p className="section-kicker">Next human task</p><h2>{b.ai_proposals.some((x)=>x.status==="proposed")?"复核AIProposal":"补齐授权Evidence与关键假设"}</h2><p>系统不会自动发布、分配预算或作出上市决定。</p></section></aside></div></>;
}

function Insights({busy,run}:{busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){
  const {localBundle:b,mutateLocal}=useProductWorkbench();const [draft,setDraft]=useState({title:"",publisher:"",raw_text:"",summary:"",applicable_scope:"",limitations:""});if(!b)return null;
  return <div className="local-two-column"><section className="panel-surface"><p className="section-kicker">Authorized material</p><h2>手工录入Evidence草稿</h2><form className="form-grid mt-5" onSubmit={(e)=>{e.preventDefault();void run(()=>mutateLocal(`/api/v1/projects/${b.project.id}/evidence/manual`,"POST",draft),"Evidence草稿已保存；尚未关联Assumption。")}}><Field label="材料标题" value={draft.title} set={(v)=>setDraft({...draft,title:v})}/><Field label="来源/发布方" value={draft.publisher} set={(v)=>setDraft({...draft,publisher:v})}/><Field label="原始内容" value={draft.raw_text} set={(v)=>setDraft({...draft,raw_text:v})} area/><Field label="摘要（人工）" value={draft.summary} set={(v)=>setDraft({...draft,summary:v})} area/><Field label="适用范围" value={draft.applicable_scope} set={(v)=>setDraft({...draft,applicable_scope:v})}/><Field label="限制" value={draft.limitations} set={(v)=>setDraft({...draft,limitations:v})}/><button disabled={busy} className="primary-action">保存Evidence草稿</button></form></section><section className="panel-surface"><p className="section-kicker">Inbox</p><h2>材料与信号收件箱</h2><div className="record-list mt-5">{b.evidence.length?b.evidence.map((item)=><article key={item.id}><div><strong>{item.title}</strong><p>{item.summary||item.raw_text.slice(0,140)}</p><small>{item.publisher||"来源待补"} · {item.origin_kind} · {item.status==="confirmed"?"人工已确认":"草稿"}</small><small>范围：{item.applicable_scope||"待补"}；限制：{item.limitations||"待补"}</small></div>{item.status==="draft"?<button className="secondary-action" disabled={busy} onClick={()=>void run(()=>mutateLocal(`/api/v1/evidence/${item.id}/confirm`,"POST"),"Evidence已人工确认；仍需建立Assumption关系。")}>人工确认</button>:<span className="meta-chip">已确认</span>}</article>):<p className="empty-inline">尚无授权材料；不会用固定夹具填充真实空间。</p>}</div></section></div>;
}

function Opportunities({busy,run}:{busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){
  const {localBundle:b,mutateLocal}=useProductWorkbench();const [packageText,setPackageText]=useState("");if(!b)return null;
  const prepare=async()=>{const refs=[b.project.id,...b.evidence.slice(0,1).map((x)=>x.id),...b.assumptions.slice(0,1).map((x)=>x.id)];const query=refs.map((ref)=>`refs=${encodeURIComponent(ref)}`).join("&");const snapshot=await api<{input_snapshot_hash:string}>(`/api/v1/projects/${b.project.id}/ai-proposals/snapshot?${query}`);setPackageText(JSON.stringify({task_type:"opportunity",input_entity_references:refs,input_snapshot_hash:snapshot.input_snapshot_hash,origin:"manual_ai_import",provider:null,model:null,prompt_template_version:"manual_template_v1",output_schema_version:"ai_proposal_v1",candidates:[{title:"全棉轻适通勤内搭机会（待验证）",description:"结构化AI建议候选；不代表市场结论。",evidence_ids:b.evidence.slice(0,1).map((x)=>x.id),contrary_evidence:[],alternatives:["沿用现有基础款"],assumption_ids:b.assumptions.slice(0,1).map((x)=>x.id),category_fit:"有纺服装字段匹配，仍需企业技术与真实研究确认"}],reasons:["仅用于说明候选结构"],contrary_evidence:[],uncertainty:["需求与供应尚未验证"],missing_inputs:b.evidence.length?[]:["confirmed_evidence"],limitations:["手工导入，不是实时Provider输出"],actor:"负责人（人工自述）"},null,2));};
  return <div className="local-two-column"><section className="panel-surface"><p className="section-kicker">AIProposal import · Provider 0</p><h2>导入结构化AI建议包</h2><p className="data-caution">导入只创建proposal。系统会校验项目内引用和输入快照；人工接受前不会生成正式Opportunity。</p><textarea className="json-import-area mt-4" aria-label="AI建议包JSON" value={packageText} onChange={(e)=>setPackageText(e.target.value)} placeholder="粘贴ai_proposal_v1 JSON"/><div className="mt-4 flex flex-wrap gap-2"><button className="secondary-action" disabled={!b.evidence.length} onClick={()=>void run(prepare,"已基于当前项目引用生成脱敏示例；未调用Provider。")}>准备当前项目示例</button><button className="primary-action" disabled={busy||!packageText} onClick={()=>void run(()=>mutateLocal(`/api/v1/projects/${b.project.id}/ai-proposals/import`,"POST",JSON.parse(packageText)),"AIProposal已导入，等待人工复核。")}>导入建议包</button></div><a className="text-link mt-4 inline-flex" href={`${runtimeConfig.apiBaseUrl}/api/v1/ai-proposals/schema`} target="_blank" rel="noreferrer">查看Schema与示例</a></section><section className="panel-surface"><p className="section-kicker">Human review queue</p><h2>建议与正式机会</h2><div className="record-list mt-5">{b.ai_proposals.map((proposal)=><ProposalCard key={proposal.id} proposal={proposal} busy={busy} run={run}/>)}{!b.ai_proposals.length?<p className="empty-inline">尚无AI建议包；Provider默认禁用。</p>:null}</div><h3 className="mt-6 font-semibold">已进入正式域的Opportunity</h3><div className="record-list mt-3">{b.opportunities.map((item)=><article key={item.id}><div><strong>{item.title}</strong><p>{item.description}</p><small>{statusName[item.status]??item.status} · Evidence {arr(item.evidence_ids_json).length} · 反证 {arr(item.contrary_evidence_json).length} · {item.data_nature}</small></div></article>)}</div></section></div>;
}

function ProposalCard({proposal,busy,run}:{proposal:AIProposal;busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){const {mutateLocal}=useProductWorkbench();return <article><div><strong>{proposal.task_type} · {statusName[proposal.status]??proposal.status}</strong><p>{arr(proposal.limitations_json).join("；")||"未填写限制"}</p><small>{proposal.origin} · {proposal.provider??"无Provider"} · input {proposal.input_snapshot_hash.slice(0,10)}…</small></div>{canReviewProposal(proposal.status,proposal.is_stale)?<div className="flex flex-wrap gap-2"><button disabled={busy} className="primary-action" onClick={()=>void run(()=>mutateLocal(`/api/v1/ai-proposals/${proposal.id}/review`,"PATCH",{decision:"accepted",reviewer:"负责人（人工自述）",review_reason:"已核验引用、限制与候选内容",candidate_index:0,revision:proposal.revision}),"候选已由人工接受并生成正式对象。")}>人工接受</button><button disabled={busy} className="secondary-action" onClick={()=>void run(()=>mutateLocal(`/api/v1/ai-proposals/${proposal.id}/review`,"PATCH",{decision:"rejected",reviewer:"负责人（人工自述）",review_reason:"当前证据不足，不采用该候选",candidate_index:0,revision:proposal.revision}),"建议已拒绝并保留理由。")}>拒绝</button></div>:null}</article>;}

function Concepts({busy,run}:{busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){
  const {localBundle:b,mutateLocal}=useProductWorkbench();const [draft,setDraft]=useState({name:"全棉轻适通勤内搭（比赛概念方案，非全棉时代正式产品）",unique_variable:"领口形态",material_hypothesis:"全棉成分待企业检测确认",specification_hypothesis:"克重与洗后稳定性待验证",price_hypothesis:"价格带尚无真实证据",supply_risk:"起订量、交期与批次一致性待供应商确认",compliance_risk:"材质与功能声明必须有Evidence支持"});if(!b)return null;const opportunity=b.opportunities.find((x)=>x.status==="confirmed")??b.opportunities[0];
  return <><section className="panel-surface"><p className="section-kicker">One-variable candidates</p><h2>创建人工产品概念候选</h2>{!opportunity?<p className="data-caution">先在Opportunity页人工确认一个机会，再创建概念。</p>:<form className="form-grid mt-5" onSubmit={(e)=>{e.preventDefault();void run(()=>mutateLocal(`/api/v1/projects/${b.project.id}/concepts`,"POST",{opportunity_id:opportunity.id,...draft,target_user:"通勤与叠穿人群假设",scenario:"日常通勤与空调办公假设",need:"降低全天穿着打扰假设",genes:["版型变量",draft.unique_variable],evidence_ids:b.evidence.filter((x)=>x.status==="confirmed").map((x)=>x.id),assumption_ids:b.assumptions.map((x)=>x.id),selection_reason:"待人工比较",status:"candidate",locked:false,actor:"负责人（人工自述）",data_nature:"real_entry"}),"产品概念候选已持久化。")}}>{Object.entries(draft).map(([key,value])=><Field key={key} label={({name:"概念名称",unique_variable:"唯一主变量",material_hypothesis:"材质假设",specification_hypothesis:"规格假设",price_hypothesis:"价格假设",supply_risk:"供应风险",compliance_risk:"合规风险"} as Record<string,string>)[key]??key} value={value} set={(v)=>setDraft({...draft,[key]:v})} area={key.includes("risk")}/>) }<button className="primary-action" disabled={busy}>保存候选概念</button></form>}</section><section className="concept-grid mt-5">{b.concepts.map((concept)=><ConceptCard key={concept.id} concept={concept} busy={busy} run={run}/>)}{!b.concepts.length?<div className="panel-surface empty-inline">尚无正式产品概念；不会用旧非织造夹具填充。</div>:null}</section></>;
}

function ConceptCard({concept,busy,run}:{concept:ProductConcept;busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){const {mutateLocal}=useProductWorkbench();const [variable,setVariable]=useState(concept.unique_variable),[reason,setReason]=useState(concept.selection_reason);return <article className="panel-surface"><div className="panel-title-row"><div><p className="section-kicker">{concept.data_nature} · V{concept.version}</p><h2>{concept.name}</h2></div><span className="meta-chip">{statusName[concept.status]??concept.status}{concept.is_stale?" · stale":""}</span></div><p>{concept.need}</p><dl className="compact-facts"><div><dt>产品基因</dt><dd>{arr(concept.genes_json).join("、")||"待补"}</dd></div><div><dt>材质</dt><dd>{concept.material_hypothesis||"待确认"}</dd></div><div><dt>供应</dt><dd>{concept.supply_risk||"待确认"}</dd></div><div><dt>声明</dt><dd>{concept.compliance_risk||"待确认"}</dd></div></dl><label className="form-field mt-4"><span>唯一主变量</span><input value={variable} onChange={(e)=>setVariable(e.target.value)}/></label><label className="form-field mt-3"><span>人工选择/编辑理由</span><textarea value={reason} onChange={(e)=>setReason(e.target.value)}/></label><button className="primary-action mt-4" disabled={busy||!reason.trim()} onClick={()=>void run(()=>mutateLocal(`/api/v1/concepts/${concept.id}`,"PATCH",{unique_variable:variable,selection_reason:reason,status:"selected",locked:true,actor:"负责人（人工自述）",revision:concept.revision}),"概念已人工选择并锁定；实质变化已触发stale传播。")}>选择并锁定当前版本</button></article>;}

function Scenarios({busy,run}:{busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){
  const {localBundle:b,mutateLocal}=useProductWorkbench();if(!b)return null;const concept=b.concepts.find((x)=>x.status==="selected")??b.concepts.at(-1),opportunity=b.opportunities.find((x)=>x.status==="confirmed")??b.opportunities[0];const counts={candidate_space:0,shortlisted:0,must_validate:0,validation:0,rejected:0};b.scenarios.filter((x)=>!x.is_stale).forEach((x)=>{counts[x.status as keyof typeof counts]+=1;});const short=b.scenarios.filter((x)=>!x.is_stale&&x.status!=="rejected").slice(0,12);
  return <><section className="scenario-funnel">{Object.entries(counts).map(([key,value])=><article key={key}><span>{statusName[key]??key}</span><strong>{value}</strong></article>)}</section><section className="panel-surface mt-5"><div className="panel-title-row"><div><p className="section-kicker">Candidate space</p><h2>100个候选组合，只在漏斗中逐步复核</h2></div><button className="primary-action" disabled={busy||!concept||!opportunity||b.scenarios.some((x)=>!x.is_stale)} onClick={()=>void run(()=>mutateLocal(`/api/v1/projects/${b.project.id}/scenarios/generate`,"POST",{opportunity_id:opportunity?.id,concept_id:concept?.id,assumption_id:b.assumptions[0]?.id??null,evidence_ids:b.evidence.filter((x)=>x.status==="confirmed").map((x)=>x.id),priority_inputs:{},actor:"负责人（人工自述）"}),"4×5×5候选空间已创建；缺少输入，因此未生成总分。")}>生成候选空间</button></div><p className="data-caution">公式只在8项明确输入全部存在时计算“待验证优先级”。当前默认不填分，不输出成功率、销量或ROI。</p><div className="scenario-shortlist mt-5">{short.map((item)=><ScenarioCard key={item.id} item={item} busy={busy} run={run}/>)}{!short.length?<p className="empty-inline">尚无候选空间。</p>:null}</div></section></>;
}

function ScenarioCard({item,busy,run}:{item:ScenarioCandidate;busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){const {mutateLocal}=useProductWorkbench();const label=scenarioPriorityLabel(item.priority,arr(item.missing_inputs_json).map(String));return <article><div><strong>{item.persona} × {item.product_gene}</strong><p>{item.channel}</p><small>{label}{item.priority===null?"":` · ${item.priority_policy_version}`}</small></div><div className="flex flex-wrap gap-2"><button disabled={busy} className="secondary-action" onClick={()=>void run(()=>mutateLocal(`/api/v1/scenarios/${item.id}`,"PATCH",{status:"shortlisted",owner:"负责人（人工自述）",review_reason:"人工加入约12项待复核短名单",actor:"负责人（人工自述）",revision:item.revision}),"候选已加入短名单。")}>加入短名单</button><button disabled={busy} className="primary-action" onClick={()=>void run(()=>mutateLocal(`/api/v1/scenarios/${item.id}`,"PATCH",{status:"validation",owner:"负责人（人工自述）",review_reason:"人工选择进入正式Validation；需在固定Gate工作区创建验证",actor:"负责人（人工自述）",revision:item.revision}),"情景已标记进入Validation；请到固定Gate工作区创建验证。")}>进入Validation</button></div></article>;}

function GateBoundary(){const {localBundle:b}=useProductWorkbench();if(!b)return null;const gate=b.gates.filter((x)=>!x.is_stale).at(-1),decision=b.decisions.filter((x)=>!x.is_stale).at(-1);return <div className="local-two-column"><section className="panel-surface"><p className="section-kicker">Fixed rule</p><h2>NDG_GATE_V0.3.0</h2><p>本页不复制或改写Gate业务规则。Evidence确认、Assumption关系、Validation阈值与结果仍在既有本地治理工作区完成。</p><Link href="/real" className="primary-action mt-5">打开Evidence与固定Gate<ArrowRight className="h-4 w-4"/></Link></section><section className="panel-surface"><p className="section-kicker">Current status</p><h2>{gate?gate.result:"尚无有效Gate"}</h2><p>{gate?`${gate.rule_version} · Round ${gate.round_number} · revision ${gate.project_revision}`:"证据不足时不会补写结论。"}</p><div className="record-list mt-4"><article><strong>人工Decision</strong><p>{decision?`${decision.decision} · ${decision.decided_by}`:"尚未人工确认"}</p></article><article><strong>AI边界</strong><p>不确认Evidence、不填结果、不修改Gate、不作最终决策。</p></article></div></section></div>;}

function Content({busy,run}:{busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){const {localBundle:b,mutateLocal}=useProductWorkbench();const [draft,setDraft]=useState({channel:"小红书",body:"",hook:"",cta:"查看待验证规格",objective:"验证规格理解",experiment_hypothesis:"明确规格和限制可能减少误解",target_user:"通勤人群假设",scenario:"日常通勤与空调办公假设",variant:"A"});if(!b)return null;const concept=b.concepts.find((x)=>x.status==="selected")??b.concepts.at(-1);return <><section className="panel-surface"><p className="section-kicker">Create one traceable asset</p><h2>创建渠道内容版本</h2>{!concept?<p className="data-caution">先选择产品概念。</p>:<form className="form-grid mt-5" onSubmit={(e)=>{e.preventDefault();void run(()=>mutateLocal(`/api/v1/projects/${b.project.id}/content-assets`,"POST",{...draft,concept_id:concept.id,opportunity_id:concept.opportunity_id,product_genes:arr(concept.genes_json),evidence_ids:arr(concept.evidence_ids_json),claim_refs:arr(concept.evidence_ids_json),visual_spec:"使用规格卡与单变量示意；不使用效果对比",actor:"负责人（人工自述）",data_nature:"real_entry"}),"内容资产已保存，确定性声明检查已运行；尚未自动批准。")}}><label className="form-field"><span>渠道</span><select value={draft.channel} onChange={(e)=>setDraft({...draft,channel:e.target.value})}>{["小红书","抖音","电商","视频号","私域"].map((x)=><option key={x}>{x}</option>)}</select></label>{Object.entries(draft).filter(([key])=>!['channel'].includes(key)).map(([key,value])=><Field key={key} label={({body:"正文/脚本",hook:"Hook",cta:"CTA",objective:"内容目标",experiment_hypothesis:"实验假设",target_user:"目标人群",scenario:"场景",variant:"A/B版本"} as Record<string,string>)[key]??key} value={value} set={(v)=>setDraft({...draft,[key]:v})} area={key==="body"||key==="experiment_hypothesis"}/>) }<button disabled={busy} className="primary-action">创建并检查</button></form>}</section><section className="panel-surface mt-5"><div className="panel-title-row"><div><p className="section-kicker">Assets and review</p><h2>内容资产与人工审核</h2></div><div className="flex gap-2">{["json","csv","markdown"].map((format)=><a key={format} className="secondary-action" href={`${runtimeConfig.apiBaseUrl}/api/v1/projects/${b.project.id}/content-assets/export?format=${format}`}><Download className="h-4 w-4"/>{format}</a>)}</div></div><div className="content-asset-grid mt-5">{b.content_assets.map((item)=><ContentCard key={item.id} item={item} busy={busy} run={run}/>)}{!b.content_assets.length?<p className="empty-inline">尚无真实内容资产。</p>:null}</div></section></>}

function ContentCard({item,busy,run}:{item:ContentAsset;busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){const {mutateLocal}=useProductWorkbench();const findings=arr(item.compliance_findings_json);return <article><div><span className="meta-chip">{item.channel} · {item.variant}</span><h3>{item.hook||"未填写Hook"}</h3><p>{item.body}</p><small>{statusName[item.review_status]??item.review_status} · V{item.version}{item.is_stale?" · stale":""}</small></div><div className="claim-findings">{findings.length?findings.map((finding,index)=><p key={index}><AlertTriangle className="h-4 w-4"/>{typeof finding==="string"?finding:JSON.stringify(finding)}</p>):<p><ShieldCheck className="h-4 w-4"/>未命中确定性检查规则；仍需人工审核。</p>}</div><button disabled={busy||item.review_status==="approved"} className="primary-action" onClick={()=>void run(()=>mutateLocal(`/api/v1/content-assets/${item.id}`,"PATCH",{review_status:"approved",reviewer:"内容负责人（人工自述）",review_reason:"已人工复核Evidence引用和声明边界",actor:"内容负责人（人工自述）",revision:item.revision}),"内容版本已人工审核。")}>人工审核通过</button></article>;}

function Results({busy,run}:{busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){const {localBundle:b,uploadLocal,mutateLocal}=useProductWorkbench();const file=useRef<HTMLInputElement>(null);if(!b)return null;const concept=b.concepts.find((x)=>x.status==="selected")??b.concepts.at(-1),feedback=b.feedback_records.at(-1);const template="channel,content_asset_id,window_start,window_end,source,impressions,clicks,interactions,saves,add_to_cart,conversions,metric_definition,owner,data_nature,notes\n小红书,替换为ContentAssetID,2026-08-20T00:00:00+08:00,2026-08-21T00:00:00+08:00,本地脱敏导入,100,20,15,8,5,2,请填写指标口径,负责人姓名,manual_import,不得含敏感信息\n";return <div className="local-two-column"><section className="panel-surface"><p className="section-kicker">Strict CSV import</p><h2>导入本地反馈</h2><p className="data-caution">拒绝负数、漏斗倒挂、缺少分母、未知内容版本、重复记录、时间窗不明及模拟/真实混合。</p><input ref={file} type="file" accept=".csv,text/csv" aria-label="反馈CSV文件" className="mt-5"/><div className="mt-4 flex flex-wrap gap-2"><button className="primary-action" disabled={busy} onClick={()=>{const selected=file.current?.files?.[0];if(!selected)return;void run(async()=>{const check=preflightFeedbackCsv(await selected.text());if(!check.ok)throw new Error(check.errors.slice(0,3).join("；"));const body=new FormData();body.append("file",selected);return uploadLocal(`/api/v1/projects/${b.project.id}/feedback/import`,body);},"反馈CSV已通过前端预检和后端权威校验，并写入SQLite。")}}><FileInput className="h-4 w-4"/>导入反馈CSV</button><button className="secondary-action" onClick={()=>downloadText("feedback-template.csv",template,"text/csv")}>下载模板</button></div></section><section className="panel-surface"><p className="section-kicker">Feedback → ChangeProposal</p><h2>只创建变更提案，不直接改概念</h2><div className="record-list mt-5">{b.feedback_records.map((item)=><article key={item.id}><strong>{item.channel} · {item.source}</strong><p>impressions {item.impressions} / clicks {item.clicks} / conversions {item.conversions}</p><small>{item.window_start.slice(0,10)}—{item.window_end.slice(0,10)} · {item.data_nature}</small></article>)}</div><button className="primary-action mt-5" disabled={busy||!concept||!feedback} onClick={()=>void run(()=>mutateLocal(`/api/v1/projects/${b.project.id}/change-proposals`,"POST",feedbackChangeProposal(concept!.id,feedback!.id)),"ChangeProposal已创建，正式概念尚未改变。")}>创建待审ChangeProposal</button></section></div>}

function DecisionStage({busy,run}:{busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){const {localBundle:b,mutateLocal}=useProductWorkbench();if(!b)return null;const gate=b.gates.filter((x)=>!x.is_stale).at(-1),decision=b.decisions.filter((x)=>!x.is_stale).at(-1),policy=b.recommendation_policies.at(-1);return <div className="decision-local-grid"><section className="panel-surface"><p className="section-kicker">Fixed Gate</p><h2>{gate?.result??"尚无有效Gate"}</h2><p>{gate?`${gate.rule_version} · revision ${gate.project_revision}`:"证据不足，不补写结论。"}</p><Link href="/real" className="primary-action mt-5">运行固定Gate并人工Decision</Link></section><section className="panel-surface"><p className="section-kicker">Recommendation layer</p><h2>{policy?(policy.data_insufficient?"数据不足，无法提出可靠调整":statusName[policy.status]??policy.status):"尚未生成建议层快照"}</h2><p>{policy?.rationale??"推荐层位于Gate之上，不修改Gate、预算或Decision。"}</p><button disabled={busy} className="secondary-action mt-4" onClick={()=>void run(()=>mutateLocal(`/api/v1/projects/${b.project.id}/recommendation-policies?actor=${encodeURIComponent("负责人（人工自述）")}`,"POST"),"已生成版本化建议层快照；不足时不填默认数字。")}>生成建议层快照</button></section><section className="panel-surface decision-wide"><p className="section-kicker">Pending change proposals</p><h2>待审变更</h2><div className="record-list mt-5">{b.change_proposals.map((item)=><ChangeCard key={item.id} item={item} busy={busy} run={run}/>)}{!b.change_proposals.length?<p className="empty-inline">尚无ChangeProposal。</p>:null}</div></section><section className="panel-surface decision-wide"><p className="section-kicker">Human Decision</p><h2>{decision?decision.decision:"尚未人工确认"}</h2><p>{decision?`${decision.decided_by}：${decision.rationale}`:"最终继续、补证或停止仍由负责人在固定Gate工作区确认。"}</p><small>当前项目 revision R{b.project.revision} · Round {b.project.current_round} · 审计事件 {b.audit_events.length}</small></section></div>}

function ChangeCard({item,busy,run}:{item:ChangeProposal;busy:boolean;run:(a:()=>Promise<unknown>,m:string)=>Promise<void>}){const {mutateLocal}=useProductWorkbench();return <article><div><strong>{item.target_entity_type} · {statusName[item.status]??item.status}</strong><p>{item.rationale}</p><small>{JSON.stringify(obj(item.proposed_patch_json))}{item.is_stale?" · stale":""}</small></div>{item.status==="proposed"&&!item.is_stale?<div className="flex gap-2"><button disabled={busy} className="primary-action" onClick={()=>void run(()=>mutateLocal(`/api/v1/change-proposals/${item.id}/review`,"PATCH",{decision:"accepted",reviewer:"负责人（人工自述）",review_reason:"人工确认字段与来源引用",revision:item.revision}),"ChangeProposal已人工接受；下游已标记stale。")}>人工接受</button><button disabled={busy} className="secondary-action" onClick={()=>void run(()=>mutateLocal(`/api/v1/change-proposals/${item.id}/review`,"PATCH",{decision:"rejected",reviewer:"负责人（人工自述）",review_reason:"当前证据不足",revision:item.revision}),"ChangeProposal已拒绝并保留理由。")}>拒绝</button></div>:null}</article>}

function Field({label,value,set,area=false}:{label:string;value:string;set:(value:string)=>void;area?:boolean}){return <label className="form-field"><span>{label}</span>{area?<textarea required value={value} onChange={(e)=>set(e.target.value)}/>:<input required value={value} onChange={(e)=>set(e.target.value)}/>}</label>}
function Kpi({label,value,note}:{label:string;value:string;note:string}){return <article><Database className="h-5 w-5"/><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function downloadText(name:string,text:string,type:string){const blob=new Blob([text],{type:`${type};charset=utf-8`});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);}
