from __future__ import annotations

from datetime import datetime

from sqlalchemy import Boolean, CheckConstraint, DateTime, Float, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from .database import Base
from .models import new_id, utcnow


class CategoryPack(Base):
    __tablename__ = "category_packs"
    id: Mapped[str] = mapped_column(String(80), primary_key=True)
    name: Mapped[str] = mapped_column(String(160))
    version: Mapped[str] = mapped_column(String(40))
    status: Mapped[str] = mapped_column(String(20), default="active")
    category_type: Mapped[str] = mapped_column(String(80))
    description: Mapped[str] = mapped_column(Text, default="")
    config_json: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    __table_args__ = (CheckConstraint("status IN ('active','legacy','disabled')", name="ck_category_pack_status"),)


class Opportunity(Base):
    __tablename__ = "opportunities"
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=lambda: new_id("opp"))
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    title: Mapped[str] = mapped_column(String(220))
    description: Mapped[str] = mapped_column(Text)
    evidence_ids_json: Mapped[str] = mapped_column(Text, default="[]")
    contrary_evidence_json: Mapped[str] = mapped_column(Text, default="[]")
    alternatives_json: Mapped[str] = mapped_column(Text, default="[]")
    assumption_ids_json: Mapped[str] = mapped_column(Text, default="[]")
    category_fit: Mapped[str] = mapped_column(Text, default="")
    source_proposal_id: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    human_reason: Mapped[str] = mapped_column(Text, default="")
    status: Mapped[str] = mapped_column(String(20), default="candidate")
    revision: Mapped[int] = mapped_column(Integer, default=1)
    version: Mapped[int] = mapped_column(Integer, default=1)
    actor: Mapped[str] = mapped_column(String(160), default="self-declared")
    data_nature: Mapped[str] = mapped_column(String(24), default="real_entry")
    is_stale: Mapped[bool] = mapped_column(Boolean, default=False)
    stale_reason: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    __table_args__ = (CheckConstraint("status IN ('candidate','confirmed','rejected')", name="ck_opportunity_status"),)


class ProductConcept(Base):
    __tablename__ = "product_concepts"
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=lambda: new_id("con"))
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    opportunity_id: Mapped[str] = mapped_column(ForeignKey("opportunities.id", ondelete="RESTRICT"), index=True)
    source_scenario_id: Mapped[str | None] = mapped_column(String(32), nullable=True, unique=True, index=True)
    name: Mapped[str] = mapped_column(String(240))
    target_user: Mapped[str] = mapped_column(Text, default="")
    scenario: Mapped[str] = mapped_column(Text, default="")
    need: Mapped[str] = mapped_column(Text, default="")
    genes_json: Mapped[str] = mapped_column(Text, default="[]")
    material_hypothesis: Mapped[str] = mapped_column(Text, default="")
    specification_hypothesis: Mapped[str] = mapped_column(Text, default="")
    price_hypothesis: Mapped[str] = mapped_column(Text, default="")
    unique_variable: Mapped[str] = mapped_column(Text, default="")
    evidence_ids_json: Mapped[str] = mapped_column(Text, default="[]")
    assumption_ids_json: Mapped[str] = mapped_column(Text, default="[]")
    supply_risk: Mapped[str] = mapped_column(Text, default="")
    compliance_risk: Mapped[str] = mapped_column(Text, default="")
    source_proposal_id: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    selection_reason: Mapped[str] = mapped_column(Text, default="")
    status: Mapped[str] = mapped_column(String(20), default="candidate")
    locked: Mapped[bool] = mapped_column(Boolean, default=False)
    revision: Mapped[int] = mapped_column(Integer, default=1)
    version: Mapped[int] = mapped_column(Integer, default=1)
    actor: Mapped[str] = mapped_column(String(160), default="self-declared")
    data_nature: Mapped[str] = mapped_column(String(24), default="real_entry")
    is_stale: Mapped[bool] = mapped_column(Boolean, default=False)
    stale_reason: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    __table_args__ = (CheckConstraint("status IN ('candidate','selected','rejected')", name="ck_concept_status"),)


class ScenarioCandidate(Base):
    __tablename__ = "scenario_candidates"
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=lambda: new_id("scn"))
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    opportunity_id: Mapped[str] = mapped_column(ForeignKey("opportunities.id", ondelete="RESTRICT"), index=True)
    concept_id: Mapped[str | None] = mapped_column(ForeignKey("product_concepts.id", ondelete="SET NULL"), nullable=True, index=True)
    assumption_id: Mapped[str | None] = mapped_column(ForeignKey("assumptions.id", ondelete="SET NULL"), nullable=True, index=True)
    evidence_ids_json: Mapped[str] = mapped_column(Text, default="[]")
    persona: Mapped[str] = mapped_column(String(160))
    product_gene: Mapped[str] = mapped_column(String(160))
    channel: Mapped[str] = mapped_column(String(80))
    scenario: Mapped[str] = mapped_column(String(200), default="")
    priority: Mapped[float | None] = mapped_column(Float, nullable=True)
    priority_inputs_json: Mapped[str] = mapped_column(Text, default="{}")
    priority_policy_version: Mapped[str | None] = mapped_column(String(80), nullable=True)
    missing_inputs_json: Mapped[str] = mapped_column(Text, default="[]")
    rationale: Mapped[str] = mapped_column(Text, default="")
    contrary_evidence_json: Mapped[str] = mapped_column(Text, default="[]")
    owner: Mapped[str] = mapped_column(String(160), default="self-declared")
    review_reason: Mapped[str] = mapped_column(Text, default="")
    shortlisted_by: Mapped[str] = mapped_column(String(160), default="")
    shortlist_reason: Mapped[str] = mapped_column(Text, default="")
    shortlist_evidence_ids_json: Mapped[str] = mapped_column(Text, default="[]")
    shortlisted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    status: Mapped[str] = mapped_column(String(24), default="candidate_space")
    revision: Mapped[int] = mapped_column(Integer, default=1)
    version: Mapped[int] = mapped_column(Integer, default=1)
    actor: Mapped[str] = mapped_column(String(160), default="self-declared")
    data_nature: Mapped[str] = mapped_column(String(24), default="real_entry")
    is_stale: Mapped[bool] = mapped_column(Boolean, default=False)
    stale_reason: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    __table_args__ = (CheckConstraint("status IN ('candidate_space','shortlisted','must_validate','validation','rejected')", name="ck_scenario_status"),)


class ContentAsset(Base):
    __tablename__ = "content_assets"
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=lambda: new_id("cnt"))
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    concept_id: Mapped[str] = mapped_column(ForeignKey("product_concepts.id", ondelete="CASCADE"), index=True)
    opportunity_id: Mapped[str | None] = mapped_column(ForeignKey("opportunities.id", ondelete="SET NULL"), nullable=True, index=True)
    channel: Mapped[str] = mapped_column(String(80))
    target_user: Mapped[str] = mapped_column(Text, default="")
    scenario: Mapped[str] = mapped_column(Text, default="")
    objective: Mapped[str] = mapped_column(Text, default="")
    experiment_hypothesis: Mapped[str] = mapped_column(Text, default="")
    hook: Mapped[str] = mapped_column(Text, default="")
    body: Mapped[str] = mapped_column(Text, default="")
    cta: Mapped[str] = mapped_column(Text, default="")
    product_genes_json: Mapped[str] = mapped_column(Text, default="[]")
    evidence_ids_json: Mapped[str] = mapped_column(Text, default="[]")
    claim_refs_json: Mapped[str] = mapped_column(Text, default="[]")
    visual_spec: Mapped[str] = mapped_column(Text, default="")
    variant: Mapped[str] = mapped_column(String(24), default="A")
    original_snapshot: Mapped[str] = mapped_column(Text, default="")
    edited_snapshot: Mapped[str] = mapped_column(Text, default="")
    source_proposal_id: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    compliance_findings_json: Mapped[str] = mapped_column(Text, default="[]")
    review_status: Mapped[str] = mapped_column(String(20), default="pending")
    reviewer: Mapped[str] = mapped_column(String(160), default="")
    review_reason: Mapped[str] = mapped_column(Text, default="")
    review_findings_snapshot_json: Mapped[str] = mapped_column(Text, default="[]")
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    revision: Mapped[int] = mapped_column(Integer, default=1)
    version: Mapped[int] = mapped_column(Integer, default=1)
    actor: Mapped[str] = mapped_column(String(160), default="self-declared")
    data_nature: Mapped[str] = mapped_column(String(24), default="real_entry")
    is_stale: Mapped[bool] = mapped_column(Boolean, default=False)
    stale_reason: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    __table_args__ = (CheckConstraint("review_status IN ('pending','approved','changes','rejected')", name="ck_content_review"),)


class FeedbackRecord(Base):
    __tablename__ = "feedback_records"
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=lambda: new_id("fbk"))
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    content_asset_id: Mapped[str] = mapped_column(ForeignKey("content_assets.id", ondelete="CASCADE"), index=True)
    concept_id: Mapped[str] = mapped_column(ForeignKey("product_concepts.id", ondelete="CASCADE"), index=True)
    assumption_id: Mapped[str | None] = mapped_column(ForeignKey("assumptions.id", ondelete="SET NULL"), nullable=True, index=True)
    channel: Mapped[str] = mapped_column(String(80))
    window_start: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    window_end: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    source: Mapped[str] = mapped_column(String(300))
    impressions: Mapped[int] = mapped_column(Integer)
    clicks: Mapped[int] = mapped_column(Integer)
    interactions: Mapped[int] = mapped_column(Integer)
    saves: Mapped[int] = mapped_column(Integer)
    add_to_cart: Mapped[int] = mapped_column(Integer)
    conversions: Mapped[int] = mapped_column(Integer)
    metric_definition: Mapped[str] = mapped_column(Text)
    owner: Mapped[str] = mapped_column(String(160))
    notes: Mapped[str] = mapped_column(Text, default="")
    import_fingerprint: Mapped[str] = mapped_column(String(64), index=True)
    revision: Mapped[int] = mapped_column(Integer, default=1)
    version: Mapped[int] = mapped_column(Integer, default=1)
    actor: Mapped[str] = mapped_column(String(160), default="self-declared")
    data_nature: Mapped[str] = mapped_column(String(24), default="manual_import")
    is_stale: Mapped[bool] = mapped_column(Boolean, default=False)
    stale_reason: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    __table_args__ = (
        CheckConstraint("impressions >= 0 AND clicks >= 0 AND interactions >= 0 AND saves >= 0 AND add_to_cart >= 0 AND conversions >= 0", name="ck_feedback_nonnegative"),
        CheckConstraint("window_end >= window_start", name="ck_feedback_window"),
        UniqueConstraint("project_id", "import_fingerprint", name="uq_feedback_import"),
    )


class AIProposal(Base):
    __tablename__ = "ai_proposals"
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=lambda: new_id("aip"))
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    task_type: Mapped[str] = mapped_column(String(60))
    input_refs_json: Mapped[str] = mapped_column(Text, default="[]")
    input_snapshot_hash: Mapped[str] = mapped_column(String(64))
    origin: Mapped[str] = mapped_column(String(24))
    provider: Mapped[str | None] = mapped_column(String(80), nullable=True)
    model: Mapped[str | None] = mapped_column(String(120), nullable=True)
    source_description: Mapped[str] = mapped_column(Text, default="")
    source_confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    prompt_template_version: Mapped[str] = mapped_column(String(60))
    output_schema_version: Mapped[str] = mapped_column(String(60))
    candidates_json: Mapped[str] = mapped_column(Text)
    reasons_json: Mapped[str] = mapped_column(Text, default="[]")
    contrary_evidence_json: Mapped[str] = mapped_column(Text, default="[]")
    uncertainty_json: Mapped[str] = mapped_column(Text, default="[]")
    missing_inputs_json: Mapped[str] = mapped_column(Text, default="[]")
    limitations_json: Mapped[str] = mapped_column(Text, default="[]")
    status: Mapped[str] = mapped_column(String(20), default="proposed")
    reviewer: Mapped[str] = mapped_column(String(160), default="")
    review_reason: Mapped[str] = mapped_column(Text, default="")
    accepted_entity_type: Mapped[str | None] = mapped_column(String(60), nullable=True)
    accepted_entity_id: Mapped[str | None] = mapped_column(String(32), nullable=True)
    revision: Mapped[int] = mapped_column(Integer, default=1)
    version: Mapped[int] = mapped_column(Integer, default=1)
    actor: Mapped[str] = mapped_column(String(160), default="self-declared")
    data_nature: Mapped[str] = mapped_column(String(24), default="ai_proposal")
    is_stale: Mapped[bool] = mapped_column(Boolean, default=False)
    stale_reason: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    __table_args__ = (
        CheckConstraint("origin IN ('fixed_demo','manual_ai_import','provider_optional')", name="ck_ai_origin"),
        CheckConstraint("status IN ('proposed','accepted','rejected','superseded')", name="ck_ai_status"),
    )


class ChangeProposal(Base):
    __tablename__ = "change_proposals"
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=lambda: new_id("chg"))
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    target_entity_type: Mapped[str] = mapped_column(String(60))
    target_entity_id: Mapped[str] = mapped_column(String(32), index=True)
    source_proposal_id: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    feedback_ids_json: Mapped[str] = mapped_column(Text, default="[]")
    proposed_patch_json: Mapped[str] = mapped_column(Text)
    rationale: Mapped[str] = mapped_column(Text)
    contrary_evidence_json: Mapped[str] = mapped_column(Text, default="[]")
    status: Mapped[str] = mapped_column(String(20), default="proposed")
    reviewer: Mapped[str] = mapped_column(String(160), default="")
    review_reason: Mapped[str] = mapped_column(Text, default="")
    revision: Mapped[int] = mapped_column(Integer, default=1)
    version: Mapped[int] = mapped_column(Integer, default=1)
    actor: Mapped[str] = mapped_column(String(160), default="self-declared")
    data_nature: Mapped[str] = mapped_column(String(24), default="real_entry")
    is_stale: Mapped[bool] = mapped_column(Boolean, default=False)
    stale_reason: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    __table_args__ = (CheckConstraint("status IN ('proposed','accepted','rejected','superseded')", name="ck_change_status"),)


class RecommendationPolicy(Base):
    __tablename__ = "recommendation_policies"
    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=lambda: new_id("pol"))
    project_id: Mapped[str] = mapped_column(ForeignKey("projects.id", ondelete="CASCADE"), index=True)
    policy_version: Mapped[str] = mapped_column(String(80))
    dimensions_json: Mapped[str] = mapped_column(Text)
    feedback_sample_count: Mapped[int] = mapped_column(Integer, default=0)
    coverage_json: Mapped[str] = mapped_column(Text, default="{}")
    suggestion_json: Mapped[str] = mapped_column(Text, default="{}")
    rationale: Mapped[str] = mapped_column(Text, default="")
    data_insufficient: Mapped[bool] = mapped_column(Boolean, default=True)
    status: Mapped[str] = mapped_column(String(20), default="proposed")
    reviewer: Mapped[str] = mapped_column(String(160), default="")
    review_reason: Mapped[str] = mapped_column(Text, default="")
    revision: Mapped[int] = mapped_column(Integer, default=1)
    version: Mapped[int] = mapped_column(Integer, default=1)
    actor: Mapped[str] = mapped_column(String(160), default="self-declared")
    data_nature: Mapped[str] = mapped_column(String(24), default="real_entry")
    is_stale: Mapped[bool] = mapped_column(Boolean, default=False)
    stale_reason: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    __table_args__ = (CheckConstraint("status IN ('proposed','accepted','rejected','superseded')", name="ck_policy_status"),)
