"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AlertTriangle, Archive, CheckCircle2, Database, Download, Link2, LoaderCircle, PlayCircle, RefreshCw, ShieldCheck } from "lucide-react";
import { runtimeConfig } from "@/config/runtime";
import { api, Assumption, Decision, Evidence, EvidenceLink, Gate, Project, ValidationTest } from "@/lib/real-api";

type Bundle={evidence:Evidence[];assumptions:Assumption[];links:EvidenceLink[];tests:ValidationTest[];gates:Gate[];decisions:Decision[]};
const emptyBundle:Bundle={evidence:[],assumptions:[],links:[],tests:[],gates:[],decisions:[]};
const gateLabel={CONTINUE:"继续投入",SUPPLEMENT:"先补证",STOP:"停止"};

export default function RealWorkspacePage(){
  const [projects,setProjects]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[bundle,setBundle]=useState<Bundle>(emptyBundle);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [newProject,setNewProject]=useState({name:"",decision_question:"",description:"",product_category:"",target_user:""});
  const [manual,setManual]=useState({title:"",publisher:"",raw_text:"",summary:""}),[url,setUrl]=useState("");
  const [assumption,setAssumption]=useState({statement:"",criticality:5}),[testDraft,setTestDraft]=useState({assumption_id:"",name:"",method:"",estimated_cost:0,estimated_days:1,success_criterion:""});

  const loadBundle=useCallback(async(p:Project)=>{const id=p.id;const [evidence,assumptions,links,tests,gates,decisions]=await Promise.all([api<Evidence[]>(`/api/v1/projects/${id}/evidence`),api<Assumption[]>(`/api/v1/projects/${id}/assumptions`),api<EvidenceLink[]>(`/api/v1/projects/${id}/links`),api<ValidationTest[]>(`/api/v1/projects/${id}/tests`),api<Gate[]>(`/api/v1/projects/${id}/gates`),api<Decision[]>(`/api/v1/projects/${id}/decisions`)]);setBundle({evidence,assumptions,links,tests,gates,decisions});},[]);
  const refresh=useCallback(async(selectedId?:string)=>{setError("");try{const list=await api<Project[]>("/api/v1/projects");setProjects(list);const selected=list.find(p=>p.id===(selectedId??project?.id))??list[0]??null;setProject(selected);if(selected)await loadBundle(selected);else setBundle(emptyBundle);}catch(e){setError(e instanceof Error?e.message:"后端不可用");}finally{setLoading(false)}},[loadBundle,project?.id]);
  useEffect(()=>{if(runtimeConfig.isLocalIntegrated)void refresh();else setLoading(false)},[]);// eslint-disable-line react-hooks/exhaustive-deps
  const act=async(fn:()=>Promise<void>,message:string)=>{if(busy)return;setBusy(true);setError("");setNotice("");try{await fn();setNotice(message)}catch(e){setError(e instanceof Error?e.message:"操作失败")}finally{setBusy(false)}};
  const createProject=(e:FormEvent)=>{e.preventDefault();void act(async()=>{const created=await api<Project>("/api/v1/projects",{method:"POST",body:JSON.stringify(newProject)});setNewProject({name:"",decision_question:"",description:"",product_category:"",target_user:""});await refresh(created.id)},"真实项目已写入SQLite")};
  const mutate=async(path:string,method="POST",body?:unknown)=>{await api(path,{method,body:body===undefined?undefined:JSON.stringify(body)});if(project)await refresh(project.id)};
  const currentGate=bundle.gates.find(x=>!x.is_stale&&x.project_revision===project?.revision),currentDecision=bundle.decisions.find(x=>!x.is_stale&&x.project_revision===project?.revision);

  if(!runtimeConfig.isLocalIntegrated)return <Boundary title="公开构建未开放真实项目" body="GitHub Pages仅运行public_demo。请在本地使用local_integrated启动真实闭环。"/>;
  if(loading)return <Boundary title="正在连接本地数据库" body="正在读取项目、Evidence和历史决策。" loading/>;
  return <div className="page-frame real-workspace" data-testid="real-workspace">
    <div className="page-heading"><div><p className="section-kicker">v0.2.0 · Local integrated</p><h1>真实项目闭环</h1><p className="page-description">单用户本地MVP：所有真实记录只写入FastAPI连接的SQLite，不使用浏览器存储兜底。</p></div><button className="secondary-action" disabled={busy} onClick={()=>void refresh()}><RefreshCw className="h-4 w-4"/>刷新</button></div>
    {error?<div className="service-status unavailable" role="alert"><AlertTriangle className="h-5 w-5"/><div><strong>操作未完成</strong><p>{error}</p></div></div>:null}{notice?<div className="service-status available" role="status"><CheckCircle2 className="h-5 w-5"/><div><strong>{notice}</strong></div></div>:null}
    <section className="real-project-bar"><div><strong>项目</strong><select aria-label="选择真实项目" value={project?.id??""} onChange={async e=>{const p=projects.find(x=>x.id===e.target.value)??null;setProject(p);if(p)await loadBundle(p)}}><option value="">请选择</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name} · r{p.revision}</option>)}</select></div>{project?<><span className="meta-chip">{project.id}</span><span className="meta-chip">revision {project.revision}</span><button className="secondary-action" onClick={()=>void act(()=>mutate(`/api/v1/projects/${project.id}/archive`),"项目已归档")}><Archive className="h-4 w-4"/>归档</button><a className="secondary-action" href={`${runtimeConfig.apiBaseUrl}/api/v1/projects/${project.id}/export`} download><Download className="h-4 w-4"/>导出JSON</a></>:null}</section>
    {!project?<section className="panel-surface"><h2 className="text-xl font-semibold">创建第一个真实项目</h2><ProjectForm value={newProject} setValue={setNewProject} submit={createProject} busy={busy}/></section>:<>
      <section className="real-gate-overview"><div className={`real-gate ${currentGate?.result.toLowerCase()??"missing"}`}><span>当前有效Gate</span><strong>{currentGate?gateLabel[currentGate.result]:"需要评估"}</strong><small>{currentGate?`revision ${currentGate.project_revision}`:"底层数据已变化或尚未计算"}</small></div><div><p className="section-kicker">Current decision</p><h2>{currentDecision?gateLabel[currentDecision.decision]:"当前没有有效Decision"}</h2><p>{currentDecision?.next_action??"请完成证据、假设与验证后执行Gate。旧结论不会继续显示为有效。"}</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} className="primary-action" onClick={()=>void act(()=>mutate(`/api/v1/projects/${project.id}/gate`),"Gate已按当前数据重新计算")}><PlayCircle className="h-4 w-4"/>执行Gate</button><button disabled={busy||!currentGate} className="secondary-action" onClick={()=>void act(()=>mutate(`/api/v1/projects/${project.id}/decision`),"可追溯Decision已生成")}><ShieldCheck className="h-4 w-4"/>生成Decision</button></div></div></section>
      <div className="real-grid">
        <section className="panel-surface"><Step number="01" title="项目问题"/><form className="form-grid mt-5" onSubmit={e=>{e.preventDefault();void act(()=>mutate(`/api/v1/projects/${project.id}`,"PATCH",{name:project.name,description:project.description,product_category:project.product_category,target_user:project.target_user,decision_question:project.decision_question,revision:project.revision}),"项目已更新")}}><Field label="项目名称" value={project.name} onChange={v=>setProject({...project,name:v})}/><Field label="产品品类" value={project.product_category} onChange={v=>setProject({...project,product_category:v})}/><Field label="目标用户" value={project.target_user} onChange={v=>setProject({...project,target_user:v})}/><Field label="决策问题" value={project.decision_question} onChange={v=>setProject({...project,decision_question:v})}/><button className="primary-action" disabled={busy}>保存项目修改</button></form></section>
        <section className="panel-surface"><Step number="02" title="Evidence录入与确认"/><form className="mt-5 space-y-3" onSubmit={e=>{e.preventDefault();void act(async()=>{await mutate(`/api/v1/projects/${project.id}/evidence/manual`,"POST",manual);setManual({title:"",publisher:"",raw_text:"",summary:""})},"手工Evidence已保存为draft")}}><Field label="标题" value={manual.title} onChange={v=>setManual({...manual,title:v})}/><Field label="来源/发布方" value={manual.publisher} onChange={v=>setManual({...manual,publisher:v})}/><Field label="原文或研究记录" value={manual.raw_text} onChange={v=>setManual({...manual,raw_text:v})} textarea/><Field label="摘要（可空）" value={manual.summary} onChange={v=>setManual({...manual,summary:v})}/><button className="primary-action" disabled={busy}>保存draft Evidence</button></form><form className="mt-4 flex gap-2" onSubmit={e=>{e.preventDefault();void act(async()=>{await mutate(`/api/v1/projects/${project.id}/evidence/url`,"POST",{url});setUrl("")},"公开URL已采集为draft")}}><input required type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://公开可访问页面"/><button className="secondary-action" disabled={busy}>采集单URL</button></form><div className="record-list">{bundle.evidence.map(item=><article key={item.id} id={item.id}><div><strong>{item.title}</strong><p>{item.summary||item.raw_text.slice(0,120)}</p><small>{item.source_type} · {item.publisher||"未填写来源"} · {item.status}</small></div><button className={item.status==="confirmed"?"secondary-action":"primary-action"} onClick={()=>void act(()=>mutate(`/api/v1/evidence/${item.id}/${item.status==="confirmed"?"unconfirm":"confirm"}`),item.status==="confirmed"?"Evidence已取消确认":"Evidence已确认并可参与Gate")}>{item.status==="confirmed"?"取消确认":"人工确认"}</button></article>)}</div></section>
        <section className="panel-surface"><Step number="03" title="关键假设与证据关系"/><form className="form-grid mt-5" onSubmit={e=>{e.preventDefault();void act(async()=>{await mutate(`/api/v1/projects/${project.id}/assumptions`,"POST",assumption);setAssumption({statement:"",criticality:5})},"关键假设已创建")}}><Field label="假设陈述" value={assumption.statement} onChange={v=>setAssumption({...assumption,statement:v})}/><label className="form-field"><span>关键度1—5</span><input type="number" min="1" max="5" value={assumption.criticality} onChange={e=>setAssumption({...assumption,criticality:Number(e.target.value)})}/></label><button className="primary-action" disabled={busy}>创建假设</button></form><div className="record-list">{bundle.assumptions.map(a=><AssumptionCard key={a.id} item={a} evidence={bundle.evidence} links={bundle.links} busy={busy} act={act} mutate={mutate}/>)}</div></section>
        <section className="panel-surface"><Step number="04" title="最低成本验证与结果"/><form className="form-grid mt-5" onSubmit={e=>{e.preventDefault();void act(async()=>{await mutate(`/api/v1/projects/${project.id}/tests`,"POST",testDraft);setTestDraft({assumption_id:"",name:"",method:"",estimated_cost:0,estimated_days:1,success_criterion:""})},"ValidationTest已创建")}}><label className="form-field"><span>关联假设</span><select required value={testDraft.assumption_id} onChange={e=>setTestDraft({...testDraft,assumption_id:e.target.value})}><option value="">请选择</option>{bundle.assumptions.map(a=><option key={a.id} value={a.id}>{a.statement}</option>)}</select></label><Field label="验证名称" value={testDraft.name} onChange={v=>setTestDraft({...testDraft,name:v})}/><Field label="方法" value={testDraft.method} onChange={v=>setTestDraft({...testDraft,method:v})}/><Field label="成功标准" value={testDraft.success_criterion} onChange={v=>setTestDraft({...testDraft,success_criterion:v})}/><label className="form-field"><span>预计成本</span><input type="number" min="0" value={testDraft.estimated_cost} onChange={e=>setTestDraft({...testDraft,estimated_cost:Number(e.target.value)})}/></label><label className="form-field"><span>预计天数</span><input type="number" min="0" value={testDraft.estimated_days} onChange={e=>setTestDraft({...testDraft,estimated_days:Number(e.target.value)})}/></label><button className="primary-action" disabled={busy}>创建验证</button></form><div className="record-list">{bundle.tests.map(t=><article key={t.id} id={t.id}><div><strong>{t.name}</strong><p>{t.method}</p><small>¥{t.estimated_cost} · {t.estimated_days}天 · {t.status}/{t.result}</small></div><div className="flex flex-wrap gap-2"><button className="secondary-action" onClick={()=>void act(()=>mutate(`/api/v1/tests/${t.id}`,"PATCH",{status:"running"}),"验证已开始")}>开始</button>{(["pass","inconclusive","fail"] as const).map(r=><button key={r} className="secondary-action" onClick={()=>void act(()=>mutate(`/api/v1/tests/${t.id}`,"PATCH",{result:r,result_notes:`人工录入结果：${r}`}),`验证结果已录入：${r}`)}>{r}</button>)}</div></article>)}</div></section>
      </div>
      <section className="panel-surface mt-5"><Step number="05" title="Gate与Decision历史（历史不覆盖）"/><div className="history-grid mt-5"><History title="Gate历史" items={bundle.gates.map(x=>({id:x.id,label:gateLabel[x.result],meta:`r${x.project_revision} · ${x.is_stale?"已失效":"当前有效"}`,detail:JSON.parse(x.reasons).map((r:{rule:string})=>r.rule).join("、")||"全部关键假设满足"}))}/><History title="Decision历史" items={bundle.decisions.map(x=>({id:x.id,label:gateLabel[x.decision],meta:`r${x.project_revision} · ${x.is_stale?"已失效":"当前有效"}`,detail:x.next_action}))}/></div></section>
    </>}
  </div>
}

function Boundary({title,body,loading=false}:{title:string;body:string;loading?:boolean}){return <div className="page-frame"><div className="empty-state">{loading?<LoaderCircle className="h-8 w-8 animate-spin"/>:<Database className="h-8 w-8"/>}<h1>{title}</h1><p>{body}</p></div></div>}
function Step({number,title}:{number:string;title:string}){return <div className="panel-title-row"><div><p className="section-kicker">Step {number}</p><h2>{title}</h2></div></div>}
function Field({label,value,onChange,textarea=false,required=true}:{label:string;value:string;onChange:(v:string)=>void;textarea?:boolean;required?:boolean}){return <label className="form-field"><span>{label}</span>{textarea?<textarea required={required} value={value} onChange={e=>onChange(e.target.value)}/>:<input required={required} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function ProjectForm({value,setValue,submit,busy}:{value:{name:string;decision_question:string;description:string;product_category:string;target_user:string};setValue:(v:typeof value)=>void;submit:(e:FormEvent)=>void;busy:boolean}){return <form className="form-grid mt-5" onSubmit={submit}><Field label="项目名称" value={value.name} onChange={v=>setValue({...value,name:v})}/><Field label="决策问题" value={value.decision_question} onChange={v=>setValue({...value,decision_question:v})}/><Field label="描述（可空）" value={value.description} onChange={v=>setValue({...value,description:v})} required={false}/><Field label="产品品类（可空）" value={value.product_category} onChange={v=>setValue({...value,product_category:v})} required={false}/><Field label="目标用户（可空）" value={value.target_user} onChange={v=>setValue({...value,target_user:v})} required={false}/><button className="primary-action" disabled={busy}>创建真实项目</button></form>}
function AssumptionCard({item,evidence,links,busy,act,mutate}:{item:Assumption;evidence:Evidence[];links:EvidenceLink[];busy:boolean;act:(fn:()=>Promise<void>,m:string)=>Promise<void>;mutate:(p:string,m?:string,b?:unknown)=>Promise<void>}){const [evidenceId,setEvidenceId]=useState(""),[direction,setDirection]=useState<"support"|"contradict">("support"),[strength,setStrength]=useState(3);return <article id={item.id}><div><strong>{item.statement}</strong><small>criticality {item.criticality}</small>{links.filter(l=>l.assumption_id===item.id).map(l=><p key={l.id}>{l.direction} · strength {l.strength} · <a href={`#${l.evidence_id}`}>{l.evidence_id}</a></p>)}</div><form className="relation-form" onSubmit={e=>{e.preventDefault();void act(()=>mutate(`/api/v1/assumptions/${item.id}/links`,"POST",{evidence_id:evidenceId,direction,strength}),"Evidence关系已建立")}}><select required value={evidenceId} onChange={e=>setEvidenceId(e.target.value)}><option value="">选择Evidence</option>{evidence.map(x=><option key={x.id} value={x.id}>{x.title} · {x.status}</option>)}</select><select value={direction} onChange={e=>setDirection(e.target.value as typeof direction)}><option value="support">support</option><option value="contradict">contradict</option></select><input aria-label="关系强度" type="number" min="1" max="5" value={strength} onChange={e=>setStrength(Number(e.target.value))}/><button className="secondary-action" disabled={busy}><Link2 className="h-4 w-4"/>关联</button></form></article>}
function History({title,items}:{title:string;items:{id:string;label:string;meta:string;detail:string}[]}){return <div><h3>{title}</h3>{items.length?items.map(x=><article key={x.id}><strong>{x.label}</strong><span>{x.meta}</span><p>{x.detail}</p><small>{x.id}</small></article>):<p className="empty-inline">尚无历史记录</p>}</div>}
